/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'data.x86.bin_20221113031206'
*/


#include "types.h"
#include "sm_rtl.h"

#pragma pack(push, 1)

/* 2 */
typedef struct PlmHeader_Size4 {
  VoidP func_ptr;
  VoidP instr_list_ptr;
} PlmHeader_Size4;

/* 3 */
typedef struct FxDef {
  uint16 door_ptr;
  uint16 base_y_pos;
  uint16 target_y_pos;
  uint16 y_vel;
  uint8 timer;
  uint8 type;
  uint8 default_layer_blend;
  uint8 layer3_layer_blend;
  uint8 fx_liquid_options_;
  uint8 palette_fx_bitset;
  uint8 animtiles_bitset;
  uint8 palette_blend;
} FxDef;

/* 4 */
typedef struct LoadStationList {
  VoidP room_ptr;
  VoidP door_ptr;
  uint16 door_bts;
  uint16 screen_x_pos;
  uint16 screen_y_pos;
  uint16 samus_y_offset;
  uint16 samus_x_offset;
} LoadStationList;

/* 5 */
typedef struct  DebugDoorDef {
  VoidP room_definition_ptr;
  uint8 door_bitflags;
  uint8 door_orientation;
  uint8 x_pos_plm;
  uint8 y_pos_plm;
  uint8 x_pos_in_room;
  uint8 y_pos_in_room;
  uint8 field_8;
  uint16 field_9;
} DebugDoorDef;

/* 6 */
typedef struct XraySpecialCasing {
  uint8 x_block;
  uint8 y_block;
  uint16 level_data_block;
} XraySpecialCasing;

/* 7 */

/* 8 */
typedef struct RoomPlmEntry {
  VoidP plm_header_ptr_;
  uint8 x_block;
  uint8 y_block;
  uint16 plm_room_argument;
} RoomPlmEntry;

/* 9 */
typedef struct PlmHeader_Size6 {
  VoidP func_ptr;
  VoidP instr_list_1_ptr;
  VoidP instr_list_2_ptr;
} PlmHeader_Size6;

/* 10 */
typedef struct MsgBoxConfig {
  VoidP modify_box_func;
  VoidP draw_initial_tilemap;
  VoidP message_tilemap;
} MsgBoxConfig;

/* 11 */
typedef struct EnemyProjectileDef {
  VoidP init_code_ptr;
  VoidP pre_instr_ptr;
  VoidP instr_list;
  uint16 radius;
  uint16 properties;
  VoidP hit_instruction_list;
  VoidP shot_instruction_list;
} EnemyProjectileDef;

/* 12 */
typedef struct Eproj_InitXYVelRandom_Args {
  VoidP field_0;
  uint16 field_2;
  uint16 field_4;
  uint16 field_6;
  uint16 field_8;
} Eproj_InitXYVelRandom_Args;

/* 84 */
typedef uint16 uint16;

/* 13 */
typedef struct EnemyData {
  uint16 enemy_ptr;
  uint16 x_pos;
  uint16 x_subpos;
  uint16 y_pos;
  uint16 y_subpos;
  uint16 x_width;
  uint16 y_height;
  uint16 properties;
  uint16 extra_properties;
  uint16 ai_handler_bits;
  uint16 health;
  uint16 spritemap_pointer;
  uint16 timer;
  uint16 current_instruction;
  uint16 instruction_timer;
  uint16 palette_index;
  uint16 vram_tiles_index;
  uint16 layer;
  uint16 flash_timer;
  uint16 frozen_timer;
  uint16 invincibility_timer;
  uint16 shake_timer;
  uint16 frame_counter;
  uint8 bank;
  uint8 field_2F;
  uint16 ai_var_A;
  uint16 ai_var_B;
  uint16 ai_var_C;
  uint16 ai_var_D;
  uint16 ai_var_E;
  uint16 ai_preinstr;
  uint16 parameter_1;
  uint16 parameter_2;
} EnemyData;

typedef struct EnemyBase {
  uint16 enemy_ptr;
  uint16 x_pos;
  uint16 x_subpos;
  uint16 y_pos;
  uint16 y_subpos;
  uint16 x_width;
  uint16 y_height;
  uint16 properties;
  uint16 extra_properties;
  uint16 ai_handler_bits;
  uint16 health;
  uint16 spritemap_pointer;
  uint16 timer;
  uint16 current_instruction;
  uint16 instruction_timer;
  uint16 palette_index;
  uint16 vram_tiles_index;
  uint16 layer;
  uint16 flash_timer;
  uint16 frozen_timer;
  uint16 invincibility_timer;
  uint16 shake_timer;
  uint16 frame_counter;
  uint8 bank;
  uint8 field_2F;
} EnemyBase;


/* 14 */
typedef struct AnimtilesDef {
  VoidP instruction_list;
  uint16 size;
  uint16 vram_addr;
} AnimtilesDef;

/* 15 */
typedef struct HdmaScrollEntry {
  uint16 top_pos;
  uint16 scroll_subspeed;
  uint16 scroll_speed;
  VoidP hdma_data_table_entry;
}HdmaScrollEntry;

/* 16 */
typedef struct SpawnHdmaObject_Args {
  uint8 field_0;
  uint8 field_1;
  VoidP addr;
}SpawnHdmaObject_Args;

/* 17 */
typedef struct CinematicSpriteObjectDef {
  VoidP init_func;
  VoidP pre_instr_func;
  VoidP instr_list;
}CinematicSpriteObjectDef;

/* 18 */
typedef struct Mode7ObjectDef {
  VoidP field_0;
  VoidP field_2;
  VoidP field_4;
}Mode7ObjectDef;

/* 19 */
typedef struct Mode7TransferData {
  uint8 field_0;
}Mode7TransferData;

/* 20 */
typedef struct CinematicBgObjectDef {
  VoidP init_func;
  VoidP pre_instr_func;
  VoidP instr_list;
}CinematicBgObjectDef;

/* 21 */
typedef struct PalFxDef {
  VoidP func;
  VoidP instrs;
}PalFxDef;

/* 22 */
typedef struct RoomDefStateSelect_E6E5_Finish {
  VoidP code_ptr;
}RoomDefStateSelect_E6E5_Finish;

/* 23 */
typedef struct LoadBg_E {
  uint16 field_0;
  uint16 field_2;
}LoadBg_E;


/* 25 */
typedef struct LoadBg_4 {
  uint16 field_0;
}LoadBg_4;

/* 26 */
enum LoadLibaryOpcode {
  kLoadLibOp_0_DONE = 0x0,
  kLoadBg_2_TransferToVram = 0x2,
  kLoadBg_4_Decompress = 0x4,
  kLoadLibOp_6_ClearFxTilemap = 0x6,
  kLoadBg_8_TransferToVramSetBG3 = 0x8,
  kLoadLibaryOpcode_A_ClearBG2Tilemap = 0xA,
  kLoadLibaryOpcode_C_ClearKraidLayer2 = 0xC,
  kLoadBg_E_DoorDepXferVram = 0xE,
};

/* 27 */
typedef struct DoorDef {
  VoidP room_definition_ptr;
  uint8 door_bitflags;
  uint8 door_orientation;
  uint8 x_pos_plm;
  uint8 y_pos_plm;
  uint8 x_pos_in_room;
  uint8 y_pos_in_room;
  uint16 samus_distance_from_door;
  VoidP door_setup_code;
}DoorDef;

/* 28 */
typedef enum SamusPose {
  kPose_00_FaceF_Powersuit = 0x0,
  kPose_01_FaceR_Normal = 0x1,
  kPose_02_FaceL_Normal = 0x2,
  kPose_03_FaceR_AimU = 0x3,
  kPose_04_FaceL_AimU = 0x4,
  kPose_05_FaceR_AimUR = 0x5,
  kPose_06_FaceL_AimUL = 0x6,
  kPose_07_FaceR_AimDR = 0x7,
  kPose_08_FaceL_AimDL = 0x8,
  kPose_09_MoveR_NoAim = 0x9,
  kPose_0A_MoveL_NoAim = 0xA,
  kPose_0B_MoveR_Gun = 0xB,
  kPose_0C_MoveL_Gun = 0xC,
  kPose_0F_MoveR_AimUR = 0xF,
  kPose_10_MoveL_AimUL = 0x10,
  kPose_11_MoveR_AimDR = 0x11,
  kPose_12_MoveL_AimDL = 0x12,
  kPose_13_FaceR_Jump_NoAim_NoMove_Gun = 0x13,
  kPose_14_FaceL_Jump_NoAim_NoMove_Gun = 0x14,
  kPose_15_FaceR_Jump_AimU = 0x15,
  kPose_16_FaceL_Jump_AimU = 0x16,
  kPose_17_FaceR_Jump_AimD = 0x17,
  kPose_18_FaceL_Jump_AimD = 0x18,
  kPose_19_FaceR_SpinJump = 0x19,
  kPose_1A_FaceL_SpinJump = 0x1A,
  kPose_1B_FaceR_SpaceJump = 0x1B,
  kPose_1C_FaceL_SpaceJump = 0x1C,
  kPose_1D_FaceR_Morphball_Ground = 0x1D,
  kPose_1E_MoveR_Morphball_Ground = 0x1E,
  kPose_1F_MoveL_Morphball_Ground = 0x1F,
  kPose_25_FaceR_Turn_Stand = 0x25,
  kPose_26_FaceL_Turn_Stand = 0x26,
  kPose_27_FaceR_Crouch = 0x27,
  kPose_28_FaceL_Crouch = 0x28,
  kPose_29_FaceR_Fall = 0x29,
  kPose_2A_FaceL_Fall = 0x2A,
  kPose_2B_FaceR_Fall_AimU = 0x2B,
  kPose_2C_FaceL_Fall_AimU = 0x2C,
  kPose_2D_FaceR_Fall_AimD = 0x2D,
  kPose_2E_FaceL_Fall_AimD = 0x2E,
  kPose_2F_FaceR_Turn_Jump = 0x2F,
  kPose_30_FaceL_Turn_Jump = 0x30,
  kPose_31_FaceR_Morphball_Air = 0x31,
  kPose_32_FaceL_Morphball_Air = 0x32,
  kPose_35_FaceR_CrouchTrans = 0x35,
  kPose_36_FaceL_CrouchTrans = 0x36,
  kPose_37_FaceR_MorphTrans = 0x37,
  kPose_38_FaceL_MorphTrans = 0x38,
  kPose_3B_FaceR_StandTrans = 0x3B,
  kPose_3C_FaceL_StandTrans = 0x3C,
  kPose_3D_FaceR_UnmorphTrans = 0x3D,
  kPose_3E_FaceL_UnmorphTrans = 0x3E,
  kPose_41_FaceL_Morphball_Ground = 0x41,
  kPose_43_FaceR_Turn_Crouch = 0x43,
  kPose_44_FaceL_Turn_Crouch = 0x44,
  kPose_49_FaceL_Moonwalk = 0x49,
  kPose_4A_FaceR_Moonwalk = 0x4A,
  kPose_4B_FaceR_Jumptrans = 0x4B,
  kPose_4C_FaceL_Jumptrans = 0x4C,
  kPose_4D_FaceR_Jump_NoAim_NoMove_NoGun = 0x4D,
  kPose_4E_FaceL_Jump_NoAim_NoMove_NoGun = 0x4E,
  kPose_4F_FaceL_Dmgboost = 0x4F,
  kPose_50_FaceR_Dmgboost = 0x50,
  kPose_51_FaceR_Jump_NoAim_MoveF = 0x51,
  kPose_52_FaceL_Jump_NoAim_MoveF = 0x52,
  kPose_53_FaceR_Knockback = 0x53,
  kPose_54_FaceL_Knockback = 0x54,
  kPose_55_FaceR_Jumptrans_AimU = 0x55,
  kPose_56_FaceL_Jumptrans_AimU = 0x56,
  kPose_57_FaceR_Jumptrans_AimUR = 0x57,
  kPose_58_FaceL_Jumptrans_AimUL = 0x58,
  kPose_59_FaceR_Jumptrans_AimDR = 0x59,
  kPose_5A_FaceL_Jumptrans_AimDL = 0x5A,
  kPose_5B = 0x5B,
  kPose_67_FaceR_Fall_Gun = 0x67,
  kPose_68_FaceL_Fall_Gun = 0x68,
  kPose_69_FaceR_Jump_AimUR = 0x69,
  kPose_6A_FaceL_Jump_AimUL = 0x6A,
  kPose_6B_FaceR_Jump_AimDR = 0x6B,
  kPose_6C_FaceL_Jump_AimDL = 0x6C,
  kPose_6D_FaceR_Fall_AimUR = 0x6D,
  kPose_6E_FaceL_Fall_AimUL = 0x6E,
  kPose_6F_FaceR_Fall_AimDR = 0x6F,
  kPose_70_FaceL_Fall_AimDL = 0x70,
  kPose_71_FaceR_Crouch_AimUR = 0x71,
  kPose_72_FaceL_Crouch_AimUL = 0x72,
  kPose_73_FaceR_Crouch_AimDR = 0x73,
  kPose_74_FaceL_Crouch_AimDL = 0x74,
  kPose_75_FaceL_Moonwalk_AimUL = 0x75,
  kPose_76_FaceR_Moonwalk_AimUR = 0x76,
  kPose_77_FaceL_Moonwalk_AimDL = 0x77,
  kPose_78_FaceR_Moonwalk_AimDR = 0x78,
  kPose_79_FaceR_Springball_Ground = 0x79,
  kPose_7A_FaceL_Springball_Ground = 0x7A,
  kPose_7B_MoveR_Springball_Ground = 0x7B,
  kPose_7C_MoveL_Springball_Ground = 0x7C,
  kPose_7D_FaceR_Springball_Fall = 0x7D,
  kPose_7E_FaceL_Springball_Fall = 0x7E,
  kPose_7F_FaceR_Springball_Air = 0x7F,
  kPose_80_FaceL_Springball_Air = 0x80,
  kPose_81_FaceR_Screwattack = 0x81,
  kPose_82_FaceL_Screwattack = 0x82,
  kPose_83_FaceR_Walljump = 0x83,
  kPose_84_FaceL_Walljump = 0x84,
  kPose_85_FaceR_Crouch_AimU = 0x85,
  kPose_86_FaceL_Crouch_AimU = 0x86,
  kPose_87_FaceR_Turn_Fall = 0x87,
  kPose_88_FaceL_Turn_Fall = 0x88,
  kPose_89_FaceR_Ranintowall = 0x89,
  kPose_8A_FaceL_Ranintowall = 0x8A,
  kPose_8B_FaceR_Turn_Stand_AimU = 0x8B,
  kPose_8C_FaceL_Turn_Stand_AimU = 0x8C,
  kPose_8D_FaceR_Turn_Stand_AimDR = 0x8D,
  kPose_8E_FaceL_Turn_Stand_AimDL = 0x8E,
  kPose_8F_FaceR_Turn_Air_AimU = 0x8F,
  kPose_90_FaceL_Turn_Air_AimU = 0x90,
  kPose_91_FaceR_Turn_Air_AimDDR = 0x91,
  kPose_92_FaceL_Turn_Air_AimDDL = 0x92,
  kPose_93_FaceR_Turn_Fall_AimU = 0x93,
  kPose_94_FaceL_Turn_Fall_AimU = 0x94,
  kPose_95_FaceR_Turn_Fall_AimDDR = 0x95,
  kPose_96_FaceL_Turn_Fall_AimDDL = 0x96,
  kPose_97_FaceR_Turn_Crouch_AimU = 0x97,
  kPose_98_FaceL_Turn_Crouch_AimU = 0x98,
  kPose_99_FaceR_Turn_Crouch_AimDDR = 0x99,
  kPose_9A_FaceL_Turn_Crouch_AimDDL = 0x9A,
  kPose_9B_FaceF_VariaGravitySuit = 0x9B,
  kPose_9C_FaceR_Turn_Stand_AimUR = 0x9C,
  kPose_9D_FaceL_Turn_Stand_AimUL = 0x9D,
  kPose_9E_FaceR_Turn_Air_AimUR = 0x9E,
  kPose_9F_FaceL_Turn_Air_AimUL = 0x9F,
  kPose_A0_FaceR_Turn_Fall_AimUR = 0xA0,
  kPose_A1_FaceL_Turn_Fall_AimUL = 0xA1,
  kPose_A2_FaceR_Turn_Crouch_AimUR = 0xA2,
  kPose_A3_FaceL_Turn_Crouch_AimUL = 0xA3,
  kPose_A4_FaceR_LandJump = 0xA4,
  kPose_A5_FaceL_LandJump = 0xA5,
  kPose_A6_FaceR_LandSpinJump = 0xA6,
  kPose_A7_FaceL_LandSpinJump = 0xA7,
  kPose_A8_FaceR_Grappling = 0xA8,
  kPose_A9_FaceL_Grappling = 0xA9,
  kPose_AA_FaceR_Grappling_AimDR = 0xAA,
  kPose_AB_FaceL_Grappling_AimDL = 0xAB,
  kPose_B2_FaceR_Grapple_Air = 0xB2,
  kPose_B3_FaceL_Grapple_Air = 0xB3,
  kPose_B4_FaceR_Grappling_Crouch = 0xB4,
  kPose_B5_FaceL_Grappling_Crouch = 0xB5,
  kPose_B6_FaceR_Grappling_Crouch_AimDR = 0xB6,
  kPose_B7_FaceL_Grappling_Crouch_AimDL = 0xB7,
  kPose_B8_FaceL_GrappleWalljumpPose = 0xB8,
  kPose_B9_FaceR_GrappleWalljumpPose = 0xB9,
  kPose_BA_FaceL_Draygon_NoMove_NoAim = 0xBA,
  kPose_BB_FaceL_Draygon_NoMove_AimUL = 0xBB,
  kPose_BC_FaceL_Draygon_Fire = 0xBC,
  kPose_BD_FaceL_Draygon_NoMove_AimDL = 0xBD,
  kPose_BE_FaceL_Draygon_Move = 0xBE,
  kPose_BF_FaceR_Moonwalk_TurnjumpL = 0xBF,
  kPose_C0_FaceL_Moonwalk_TurnjumpR = 0xC0,
  kPose_C1_FaceR_Moonwalk_TurnjumpL_AimUR = 0xC1,
  kPose_C2_FaceL_Moonwalk_TurnjumpR_AimUL = 0xC2,
  kPose_C3_FaceR_Moonwalk_TurnjumpL_AimDR = 0xC3,
  kPose_C4_FaceL_Moonwalk_TurnjumpR_AimDL = 0xC4,
  kPose_C7_FaceR_ShinesparkWindup_Vert = 0xC7,
  kPose_C8_FaceL_ShinesparkWindup_Vert = 0xC8,
  kPose_C9_FaceR_Shinespark_Horiz = 0xC9,
  kPose_CA_FaceL_Shinespark_Horiz = 0xCA,
  kPose_CB_FaceR_Shinespark_Vert = 0xCB,
  kPose_CC_FaceL_Shinespark_Vert = 0xCC,
  kPose_CD_FaceR_Shinespark_Diag = 0xCD,
  kPose_CE_FaceL_Shinespark_Diag = 0xCE,
  kPose_CF_FaceR_Ranintowall_AimUR = 0xCF,
  kPose_D0_FaceL_Ranintowall_AimUL = 0xD0,
  kPose_D1_FaceR_Ranintowall_AimDR = 0xD1,
  kPose_D2_FaceL_Ranintowall_AimDL = 0xD2,
  kPose_D3_FaceR_CrystalFlash = 0xD3,
  kPose_D4_FaceL_CrystalFlash = 0xD4,
  kPose_D5_FaceR_Xray_Stand = 0xD5,
  kPose_D6_FaceL_Xray_Stand = 0xD6,
  kPose_D7_FaceR_CrystalFlashEnd = 0xD7,
  kPose_D8_FaceL_CrystalFlashEnd = 0xD8,
  kPose_D9_FaceR_Xray_Crouch = 0xD9,
  kPose_DA_FaceL_Xray_Crouch = 0xDA,
  kPose_DB = 0xDB,
  kPose_E0_FaceR_LandJump_AimU = 0xE0,
  kPose_E1_FaceL_LandJump_AimU = 0xE1,
  kPose_E2_FaceR_LandJump_AimUR = 0xE2,
  kPose_E3_FaceL_LandJump_AimUL = 0xE3,
  kPose_E4_FaceR_LandJump_AimDR = 0xE4,
  kPose_E5_FaceL_LandJump_AimDL = 0xE5,
  kPose_E6_FaceR_LandJump_Fire = 0xE6,
  kPose_E7_FaceL_LandJump_Fire = 0xE7,
  kPose_E8_FaceR_Drained_CrouchFalling = 0xE8,
  kPose_E9_FaceL_Drained_CrouchFalling = 0xE9,
  kPose_EA_FaceR_Drained_Stand = 0xEA,
  kPose_EB_FaceL_Drained_Stand = 0xEB,
  kPose_EC_FaceR_Draygon_NoMove_NoAim = 0xEC,
  kPose_ED_FaceR_Draygon_NoMove_AimUR = 0xED,
  kPose_EE_FaceR_Draygon_Fire = 0xEE,
  kPose_EF_FaceR_Draygon_NoMove_AimDR = 0xEF,
  kPose_F0_FaceR_Draygon_Move = 0xF0,
  kPose_F1_FaceR_CrouchTrans_AimU = 0xF1,
  kPose_F2_FaceL_CrouchTrans_AimU = 0xF2,
  kPose_F3_FaceR_CrouchTrans_AimUR = 0xF3,
  kPose_F4_FaceL_CrouchTrans_AimUL = 0xF4,
  kPose_F5_FaceR_CrouchTrans_AimDR = 0xF5,
  kPose_F6_FaceL_CrouchTrans_AimDL = 0xF6,
  kPose_F7_FaceR_StandTrans_AimU = 0xF7,
  kPose_F8_FaceL_StandTrans_AimU = 0xF8,
  kPose_F9_FaceR_StandTrans_AimUR = 0xF9,
  kPose_FA_FaceL_StandTrans_AimUL = 0xFA,
  kPose_FB_FaceR_StandTrans_AimDR = 0xFB,
  kPose_FC_FaceL_StandTrans_AimDL = 0xFC,
} SamusPose;

/* 29 */
enum LiquidPhysicsType {
  kLiquidPhysicsType_Air = 0x0,
  kLiquidPhysicsType_Water = 0x1,
  kLiquidPhysicsType_LavaAcid = 0x2,
};

/* 30 */
typedef struct SamusPoseParams {
  uint8 pose_x_dir;
  uint8 movement_type;
  uint8 new_pose_unless_buttons;
  uint8 direction_shots_fired;
  uint8 y_offset_to_gfx;
  uint8 field_5;
  uint8 y_radius;
  uint8 field_7;
} SamusPoseParams;

/* 31 */
typedef struct SamusSpeedTableEntry {
  uint16 accel;
  uint16 accel_sub;
  uint16 max_speed;
  uint16 max_speed_sub;
  uint16 decel;
  uint16 decel_sub;
} SamusSpeedTableEntry;

/* 32 */
enum SamusMovementType {
  kMovementType_00_Standing = 0x0,
  kMovementType_01_Running = 0x1,
  kMovementType_02_NormalJumping = 0x2,
  kMovementType_03_SpinJumping = 0x3,
  kMovementType_04_MorphBallOnGround = 0x4,
  kMovementType_05_Crouching = 0x5,
  kMovementType_06_Falling = 0x6,
  kMovementType_07_Unused = 0x7,
  kMovementType_08_MorphBallFalling = 0x8,
  kMovementType_09_Unused = 0x9,
  kMovementType_0A_KnockbackOrCrystalFlashEnding = 0xA,
  kMovementType_0B_Unused = 0xB,
  kMovementType_0C_Unused = 0xC,
  kMovementType_0D_Unused = 0xD,
  kMovementType_0E_TurningAroundOnGround = 0xE,
  kMovementType_0F_CrouchingEtcTransition = 0xF,
  kMovementType_10_Moonwalking = 0x10,
  kMovementType_11_SpringBallOnGround = 0x11,
  kMovementType_12_SpringBallInAir = 0x12,
  kMovementType_13_SpringBallFalling = 0x13,
  kMovementType_14_WallJumping = 0x14,
  kMovementType_15_RanIntoWall = 0x15,
  kMovementType_16_Grappling = 0x16,
  kMovementType_17_TurningAroundJumping = 0x17,
  kMovementType_18_TurningAroundFalling = 0x18,
  kMovementType_19_DamageBoost = 0x19,
  kMovementType_1A_GrabbedByDraygon = 0x1A,
  kMovementType_1B_ShinesparkEtc = 0x1B,
};

/* 33 */
typedef struct DisableMinimapAndMarkBossRoomAsExploredEnt {
  uint16 boss_id_;
  VoidP ptrs;
} DisableMinimapAndMarkBossRoomAsExploredEnt;

/* 34 */
typedef struct ProjectileDamagesAndInstrPtr {
  unsigned int damages;
  VoidP instr_ptr;
} ProjectileDamagesAndInstrPtr;

/* 36 */
typedef struct DemoInputObject {
  VoidP ptr;
  VoidP pre_instr;
  VoidP instr_ptr;
} DemoInputObject;

/* 37 */
typedef struct DemoSetDef {
  uint16 items;
  uint16 missiles;
  uint16 super_missiles;
  uint16 power_bombs;
  uint16 health;
  uint16 beams;
  uint16 equipped_beams_;
  VoidP demo_obj;
} DemoSetDef;

/* 38 */
typedef struct DemoInputEntry {
  uint16 timer;
  uint16 input;
  uint16 input_new;
} DemoInputEntry;

/* 39 */
typedef struct PoseEntry {
  uint16 new_input;
  uint16 cur_input;
  uint16 new_pose;
} PoseEntry;

/* 40 */
typedef struct XrayBlockData {
  uint16 value;
  VoidP addr;
} XrayBlockData;

/* 41 */
typedef struct SamusCrystalFlashPalTable {
  VoidP ptr;
  uint16 timer;
} SamusCrystalFlashPalTable;

/* 42 */
typedef struct SamusTileAnimationDefs {
  uint8 top_half_idx;
  uint8 top_half_pos;
  uint8 bottom_half_idx;
  uint8 bottom_half_pos;
} SamusTileAnimationDefs;

/* 43 */
typedef struct  SamusTileAnimationTileDefs {
  uint16 src;
  uint8 gap2;
  uint16 part1_size;
  uint16 part2_size;
}SamusTileAnimationTileDefs;

/* 44 */
typedef struct ProjectileDataTable {
  uint16 damage;
  VoidP field_2;
  VoidP field_4;
  VoidP field_6;
  VoidP field_8;
  VoidP field_A;
  VoidP field_C;
  VoidP field_E;
  VoidP field_10;
  VoidP field_12;
  VoidP field_14;
} ProjectileDataTable;

/* 45 */
typedef struct ProjectileInstr {
  uint16 timer;
  VoidP spritemap_ptr;
  uint8 x_radius;
  uint8 y_radius;
  uint16 field_6;
} ProjectileInstr;

/* 46 */
typedef struct GrappleBeamSpecialAngles {
  uint16 field_0;
  uint16 field_2;
  uint16 field_4;
  uint16 field_6;
  VoidP field_8;
} GrappleBeamSpecialAngles;

/* 47 */
typedef struct ExtendedSpriteMap {
  uint16 xpos;
  uint16 ypos;
  VoidP spritemap;
  VoidP hitbox_ptr_;
} ExtendedSpriteMap;

/* 48 */
typedef struct Hitbox {
  uint16 left;
  uint16 top;
  uint16 right;
  uint16 bottom;
  VoidP func_ptr;
  VoidP func_ptrA;
} Hitbox;

/* 49 */
typedef struct EnemySpawnData {
  uint16 some_flag;
  uint16 cause_of_death;
  uint16 field_4;
  uint16 vram_tiles_index;
  uint16 palette_index;
  uint16 field_A;
  uint16 field_C;
  uint16 field_E;
  uint16 xpos2;
  uint16 ypos2;
  uint16 field_14;
  uint16 field_16;
  uint16 field_18;
  uint16 field_1A;
  uint16 field_1C;
  uint16 id;
  uint16 x_pos;
  uint16 y_pos;
  uint16 init_param;
  uint16 properties;
  uint16 extra_properties;
  uint16 param_1;
  uint16 param_2;
  uint8 name[18];
} EnemySpawnData;

/* 50 */
enum EnemyExtraProps {
  kEnemyExtraProps_DisableEnemyAI = 0x1,
  kEnemyExtraProps_MultiHitbox = 0x4,
  kEnemyExtraProps_UpdateGfx = 0x8000,
} ;

/* 52 */
enum ProjectileType {
  kProjectileType_Missile = 0x100,
  kProjectileType_SuperMissile = 0x200,
  kProjectileType_PowerBomb = 0x300,
  kProjectileType_Bomb = 0x500,
  kProjectileType_BeamExplosion = 0x700,
  kProjectileType_MissileExplosion = 0x800,
  kProjectileType_TypeMask = 0xF00,
  kProjectileType_DontInteractWithSamus = 0x8000,
};

/* 53 */
enum EnemyProps {
  kEnemyProps_Invisible = 0x100,
  kEnemyProps_Deleted = 0x200,
  kEnemyProps_Tangible = 0x400,
  kEnemyProps_ProcessedOffscreen = 0x800,
  kEnemyProps_BlockPlasmaBeam = 0x1000,
  kEnemyProps_DisableSamusColl = 0x2000,
  kEnemyProps_RespawnIfKilled = 0x4000,
};

/* 54 */
typedef struct EnemyPopulation {
  VoidP enemy_ptr;
  uint16 x_pos;
  uint16 y_pos;
  uint16 init_param;
  uint16 properties;
  uint16 extra_properties;
  uint16 parameter1;
  uint16 parameter2;
} EnemyPopulation;

/* 55 */
typedef struct EnemySetName {
  uint8 field_0[7];
} EnemySetName;

/* 56 */
typedef struct EnemyTileset {
  VoidP enemy_def;
  uint16 vram_dst;
} EnemyTileset;

/* 57 */
enum EnemyAiBits {
  kEnemyAiBits_Grapple = 0x1,
  kEnemyAiBits_Hurt = 0x2,
  kEnemyAiBits_Frozen = 0x4,
};

/* 58 */
typedef struct Vulnerability {
  uint8 power;
  uint8 wave;
  uint8 ice;
  uint8 ice_wave;
  uint8 spazer;
  uint8 spazer_wave;
  uint8 spazer_ice;
  uint8 spazer_ice_wave;
  uint8 plasma;
  uint8 plasma_wave;
  uint8 plasma_ice;
  uint8 plasma_ice_wave;
  uint8 missile;
  uint8 super_missile;
  uint8 bomb;
  uint8 power_bomb;
  uint8 speed_booster;
  uint8 shinespark;
  uint8 screw_attack;
  uint8 charged_beam;
  uint8 pseudo_screw_attack;
  uint8 field_15;
} Vulnerability;

/* 59 */
typedef struct EnemyDropChances {
  uint8 field_0;
  uint8 field_1;
  uint8 field_2;
  uint8 field_3;
  uint8 field_4;
  uint8 field_5;
} EnemyDropChances;

typedef struct SpriteDrawInstr {
  uint16 field_0;
  VoidP field_2;
} SpriteDrawInstr;

/* 70 */
typedef struct MaridiaSnailData {
  uint16 field_0;
  uint16 field_2;
  VoidP field_4;
  VoidP field_6;
} MaridiaSnailData;

/* 71 */
typedef struct MaridiaSnailData2 {
  VoidP field_0;
  uint16 field_2;
  VoidP field_4;
  uint16 field_6;
} MaridiaSnailData2;

/* 73 */
typedef struct  Mode7VramWriteQueue {
  uint8 field_0;
  uint16 field_1;
  uint8 gap3[2];
  uint16 field_5;
} Mode7VramWriteQueue;

/* 74 */
typedef struct KraidInstrList {
  uint16 timer;
  VoidP tilemap;
  VoidP vuln_mouth_hitbox;
  VoidP invuln_mouth_hitbox;
} KraidInstrList;

/* 75 */
typedef struct KraidMouthHitbox {
  uint16 field_0;
  uint16 field_2;
  uint16 field_4;
  uint16 field_6;
} KraidMouthHitbox;

/* 76 */
typedef struct KraidSinkTable {
  uint16 field_0;
  uint16 field_2;
  VoidP field_4;
} KraidSinkTable;

/* 77 */
typedef struct MotherBrainHitbox {
  uint16 field_0;
  uint16 field_2;
  uint16 field_4;
  uint16 field_6;
} MotherBrainHitbox;

/* 78 */
typedef struct ShitroidMovementTable {
  uint16 field_0;
  uint16 field_2;
  uint16 field_4;
  VoidP field_6;
} ShitroidMovementTable;

/* 79 */
typedef struct RoomPaletteInstrList {
  uint16 field_0;
  VoidP field_2;
} RoomPaletteInstrList;

/* 80 */
typedef struct CorpseRottingVramTransferDefs {
  uint16 field_0;
  uint16 field_2;
  uint16 field_4;
  uint16 field_6;
} CorpseRottingVramTransferDefs;

/* 81 */
typedef struct CorpseRottingDef {
  VoidP field_0;
  VoidP field_2;
  VoidP field_4;
  VoidP field_6;
  uint16 field_8;
  VoidP field_A;
  VoidP field_C;
  VoidP field_E;
} CorpseRottingDef;

/* 82 */
typedef struct BotwoonMovementData {
  VoidP field_0;
  uint16 field_2;
  uint16 field_4;
  uint16 field_6;
} BotwoonMovementData;

typedef struct RoomDefHeader {
  uint8 semiunique_room_number;
  uint8 area_index_;
  uint8 x_coordinate_on_map;
  uint8 y_coordinate_on_map;
  uint8 width;
  uint8 height;
  uint8 up_scroller_;
  uint8 down_scroller_;
  uint8 cre_bitset_;
  VoidP ptr_to_doorout;
} RoomDefHeader;

/* 93 */
enum GameState {
  kGameState_0_Reset = 0x0,
  kGameState_1_OpeningCinematic = 0x1,
  kGameState_2_GameOptionsMenu = 0x2,
  kGameState_3_Unused = 0x3,
  kGameState_4_FileSelectMenus = 0x4,
  kGameState_5_FileSelectMap = 0x5,
  kGameState_6_LoadingGameData = 0x6,
  kGameState_7_MainGameplayFadeIn = 0x7,
  kGameState_8_MainGameplay = 0x8,
  kGameState_9_HitDoorBlock = 0x9,
  kGameState_10_LoadingNextRoom = 0xA,
  kGameState_11_LoadingNextRoom = 0xB,
  kGameState_12_Pausing = 0xC,
  kGameState_13_Pausing = 0xD,
  kGameState_14_Paused = 0xE,
  kGameState_15_Paused = 0xF,
  kGameState_16_Unpausing = 0x10,
  kGameState_17_Unpausing = 0x11,
  kGameState_18_Unpausing = 0x12,
  kGameState_19_SamusNoHealth = 0x13,
  kGameState_20_SamusNoHealth = 0x14,
  kGameState_21_SamusNoHealth = 0x15,
  kGameState_22_SamusNoHealth = 0x16,
  kGameState_23_SamusNoHealth = 0x17,
  kGameState_24_SamusNoHealth = 0x18,
  kGameState_25_SamusNoHealth = 0x19,
  kGameState_26_GameOverMenu = 0x1A,
  kGameState_27_ReserveTanksAuto = 0x1B,
  kGameState_28_Unused = 0x1C,
  kGameState_29_DebugGameOverMenu = 0x1D,
  kGameState_30_IntroCinematic = 0x1E,
  kGameState_31_SetUpNewGame = 0x1F,
  kGameState_32_MadeItToCeresElevator = 0x20,
  kGameState_33_BlackoutFromCeres = 0x21,
  kGameState_34_CeresGoesBoom = 0x22,
  kGameState_35_TimeUp = 0x23,
  kGameState_36_WhitingOutFromTimeUp = 0x24,
  kGameState_37_CeresGoesBoomWithSamus = 0x25,
  kGameState_38_SamusEscapesFromZebes = 0x26,
  kGameState_39_EndingAndCredits = 0x27,
  kGameState_40_TransitionToDemo = 0x28,
  kGameState_41_TransitionToDemo = 0x29,
  kGameState_42_PlayingDemo = 0x2A,
  kGameState_43_TransitionFromDemo = 0x2B,
  kGameState_44_TransitionFromDemo = 0x2C,
};

/* 94 */
enum LoadingGameState {
  kLoadingGameState_0_Intro = 0x0,
  kLoadingGameState_5_Main = 0x5,
  kLoadingGameState_1F_StartingAtCeres = 0x1F,
  kLoadingGameState_22_EscapingCeres = 0x22,
};

/* 95 */
typedef enum Buttons {
  kButton_R = 0x10,
  kButton_L = 0x20,
  kButton_X = 0x40,
  kButton_A = 0x80,
  kButton_Right = 0x100,
  kButton_Left = 0x200,
  kButton_Down = 0x400,
  kButton_Up = 0x800,
  kButton_Start = 0x1000,
  kButton_Select = 0x2000,
  kButton_Y = 0x4000,
  kButton_B = 0x8000,
} Buttons;

/* 96 */
typedef struct StateHeaderTiles {
  LongPtr tile_table_ptr;
  LongPtr tiles_ptr;
  LongPtr palette_ptr;
} StateHeaderTiles;

/* 97 */
typedef struct RoomDefRoomstate {
  LongPtr compressed_room_map_ptr;
  uint8 graphics_set;
  uint8 music_track;
  uint8 music_control;
  VoidP room_layer3_fx_ptr;
  VoidP enemy_population_ptr_;
  VoidP enemy_tilesets_ptr;
  uint16 vertical_screen_nudge_limit;
  VoidP rdf_scroll_ptr;
  VoidP xray_special_casing_ptr;
  VoidP main_code_ptr;
  VoidP room_plm_header_ptr;
  VoidP bg_data_ptr;
  VoidP room_setup_code;
} RoomDefRoomstate;

/* 98 */
typedef struct RoomDefStateSelect_EBE5_Door {
  VoidP code_ptr;
  uint16 dddd;
  uint16 ssss;
} RoomDefStateSelect_EBE5_Door;

/* 99 */
typedef struct RoomDefStateSelect_FFE5_TourianBoss01 {
  VoidP code_ptr;
  uint16 ssss;
} RoomDefStateSelect_FFE5_TourianBoss01;

/* 100 */
typedef struct Ram7800_Kraid {
  uint16 kraid_next;
  uint16 field_2;
  uint16 field_4;
  uint16 kraid_thinking;
  uint16 kraid_min_y_pos_eject;
  uint16 kraid_mouth_flags;
  uint16 kraid_healths_8ths[8];
  uint16 field_1C;
  uint16 kraid_target_x;
  uint16 kraid_healths_4ths[4];
  uint16 field_28;
  uint16 kraid_hurt_frame;
  uint16 kraid_hurt_frame_timer;
} Ram7800_Kraid;

/* 101 */
typedef struct StartDmaCopy {
  uint8 chan;
  uint8 dmap;
  uint8 bbad;
  LongPtr a1;
  VoidP das;
} StartDmaCopy;

/* 103 */
typedef struct  OpcodeData3 {
  uint16 field_0;
  uint8 field_2;
} OpcodeData3;

/* 104 */
typedef struct OamEnt {
  uint8 xcoord;
  uint8 ycoord;
  uint8 charnum;
  uint8 flags;
} OamEnt;

/* 105 */
typedef struct  VramWriteEntry {
  uint16 size;
  LongPtr src;
  uint16 vram_dst;
} VramWriteEntry;

/* 106 */
typedef struct  VramReadQueueEnt {
  uint16 vram_target;
  uint16 dma_parameters;
  LongPtr src;
  uint16 size;
} VramReadQueueEnt;

/* 107 */
typedef struct  SpriteDrawEnt {
  uint16 x_and_flags;
  uint8 xcoord;
  uint16 char_flags;
} SpriteDrawEnt;

/* 108 */
typedef struct  EnemyTileLoadData {
  uint16 tile_data_size;
  LongPtr tile_data_ptr;
  uint16 offset_into_ram;
} EnemyTileLoadData;

/* 109 */
typedef struct ExpandingSquareTransitionHdma {
  uint8 field_0;
  uint8 field_1;
  uint8 field_2;
} ExpandingSquareTransitionHdma;

/* 110 */
typedef struct TileTable {
  uint16 top_left;
  uint16 top_right;
  uint16 bottom_left;
  uint16 bottom_right;
} TileTable;

/* 111 */
typedef struct TileTables {
  TileTable tables[1024];
} TileTables;

/* 112 */
typedef struct ElevatorsUsedConf {
  uint8 sourcce_area;
  uint8 source_bit;
  uint8 dest_area;
  uint8 dest_bit;
} ElevatorsUsedConf;

/* 113 */
typedef struct MenuTilemaps {
  uint16 size;
  VoidP src;
  uint16 field_4;
  VoidP vram_dst;
} MenuTilemaps;

/* 114 */
typedef struct MapIconDataPointers {
  VoidP crateria;
  VoidP brinstar;
  VoidP norfair;
  VoidP wrecked_ship;
  VoidP maraidia;
  VoidP tourian;
  VoidP ceres;
  VoidP debug;
} MapIconDataPointers;

/* 115 */
typedef struct ExpandingSquareVels {
  uint16 left_subvel;
  uint16 left_vel;
  uint16 right_subvel;
  uint16 right_vel;
  uint16 top_subvel;
  uint16 top_vel;
  uint16 bottom_subvel;
  uint16 bottom_vel;
} ExpandingSquareVels;

/* 116 */
typedef struct MapScrollArrowData {
  uint16 xpos;
  uint16 ypos;
  uint16 pause_screen_animation_id;
  uint16 joypad_input;
  uint16 map_scroll_dir;
} MapScrollArrowData;

/* 117 */
typedef struct DemoRoomData {
  VoidP room_ptr_;
  uint16 door_ptr;
  uint16 door_slot;
  uint16 screen_x_pos;
  uint16 screen_y_pos;
  uint16 samus_x_offs;
  uint16 samus_y_offs;
  uint16 demo_length;
  VoidP demo_code_ptr;
} DemoRoomData;

/* 118 */
typedef union PauseScreenSpriteAnimationData {
  struct {
    VoidP unused;
    VoidP lr_highlight;
    VoidP item_selector;
    VoidP unused2;
    VoidP unused3;
    VoidP map_scroll_arrow_up;
    VoidP map_scroll_arrow_down;
    VoidP map_scroll_arrow_right;
    VoidP map_scroll_arrow_left;
  };
  VoidP arr[9];
} PauseScreenSpriteAnimationData;

/* 119 */
typedef struct FileCopyArrowStuff {
  uint16 spritemap;
  uint16 xpos;
  uint16 ypos;
} FileCopyArrowStuff;

/* 120 */
typedef struct GameOverBabyMetroidInstruction {
  VoidP field_0;
  VoidP field_2;
  VoidP field_4;
} GameOverBabyMetroidInstruction;

/* 121 */
typedef struct  CopyToVramAtNextInterruptArgs {
  LongPtr source;
  VoidP dest;
  uint16 size;
}CopyToVramAtNextInterruptArgs;

/* 122 */
typedef struct EnemyDef_A2 {
  uint16 tile_data_size;
  VoidP palette_ptr;
  uint16 health;
  uint16 damage;
  uint16 x_radius;
  uint16 y_radius;
  uint8 bank;
  uint8 hurt_ai_time;
  uint16 hurt_sfx;
  uint16 boss_fight_value;
  VoidP ai_init;
  uint16 num_parts;
  uint16 field_16;
  VoidP main_ai;
  VoidP grapple_ai;
  VoidP hurt_ai;
  VoidP frozen_ai;
  VoidP time_is_frozen_ai;
  uint16 death_anim;
  uint16 field_24;
  uint16 field_26;
  VoidP powerbomb_reaction;
  VoidP field_2A;
  uint16 field_2C;
  uint16 field_2E;
  VoidP touch_ai;
  VoidP shot_ai;
  VoidP field_34;
  LongPtr tile_data;
  uint8 layer;
  VoidP item_drop_chances_ptr;
  VoidP vulnerability_ptr;
  VoidP name_ptr;
} EnemyDef_A2;

typedef EnemyDef_A2 EnemyDef_A3;
typedef EnemyDef_A2 EnemyDef_A4;
typedef EnemyDef_A2 EnemyDef_A5;
typedef EnemyDef_A2 EnemyDef_A6;
typedef EnemyDef_A2 EnemyDef_A7;
typedef EnemyDef_A2 EnemyDef_A8;
typedef EnemyDef_A2 EnemyDef_AA;

typedef EnemyDef_A2 EnemyDef_B2;
typedef EnemyDef_A2 EnemyDef_B3;
/* 133 */

typedef struct  Ram3000_MsgBox {
  uint8 pad[188];
  uint16 msg_box_anim_y_radius_neg[30];
  uint16 msg_box_anim_y_radius[30];
  uint8 field_134[204];
  uint16 tilemap[192];
  uint8 indirect_hdma[7];
  uint8 field_387[99];
  uint8 backup_of_enabled_hdma_channels;
  uint16 backup_of_bg3_tilemap_and_size;
} Ram3000_MsgBox;

/* 134 */
typedef struct Ram3000_Misc {
  uint8 field_0[472];
  uint16 pause_screen_samus_witeframe_tilemap[264];
  uint8 field_3E8[24];
} Ram3000_Misc;

/* 135 */
typedef struct Ram3000_Menu {
  uint8 field_0[768];
  uint16 palette_backup_in_menu[256];
  uint8 backup_of_io_registers_in_gameover[54];
  uint8 field_536[202];
  uint8 menu_tilemap[512];
} Ram3000_Menu;

/* 136 */
typedef union Ram3800 {
  uint16 cinematic_bg_tilemap[1024];
  uint16 equipment_screen_bg1_tilemap[1024];
  uint16 debug_game_over_tilemap[1024];
  uint16 cleared_message_box_bg3_tilemap[1024];
} Ram3800;

/* 137 */
typedef struct Ram4000_Backups {
  uint8 field_0[256];
  uint16 backup_of_vram_0x5880_msgbox[896];
  uint8 field_800[2048];
  uint8 backup_of_0x3e00_in_kraid_pause[1024];
} Ram4000_Backups;

/* 138 */
typedef union Ram4000 {
  uint16 xray_tilemaps[6144];
  uint16 bg2_tilemap[2048];
  uint16 decomp_buffer_kraid[1024];
  uint16 bg2_room_select_map_tilemap[1024];
  uint16 intro_japanese_text_tiles[768];
  Ram4000_Backups backups;
} Ram4000;

/* 139 */
typedef struct  Mode7CgvmWriteQueue {
  uint8 tag;
  LongPtr src_addr;
  uint16 count;
  uint16 vram_addr;
  uint8 vmain;
} Mode7CgvmWriteQueue;

/* 140 */
typedef struct  RoomDefStateSelect_29E6_BossBitFlags {
  VoidP code_ptr;
  uint8 bb;
  VoidP ssss;
} RoomDefStateSelect_29E6_BossBitFlags;

/* 141 */
typedef struct  RoomDefStateSelect_12E6_EventBitArray {
  VoidP code_ptr;
  uint8 rr;
  VoidP ssss;
} RoomDefStateSelect_12E6_EventBitArray;

/* 142 */
typedef struct RoomDefStateSelect_52E6_MorphMissile {
  VoidP code_ptr;
  uint16 ssss;
} RoomDefStateSelect_52E6_MorphMissile;

/* 143 */
typedef struct RoomDefStateSelect_69E6_PowerBombs {
  VoidP code_ptr;
  VoidP ssss;
} RoomDefStateSelect_69E6_PowerBombs;

/* 144 */
typedef struct RoomDefStateSelect_78E6_SpeedBooster {
  VoidP code_ptr;
  uint16 ssss;
} RoomDefStateSelect_78E6_SpeedBooster;

/* 151 */
typedef struct Ram7800_SpikeShootingPlant {
  uint16 var_a;
  uint16 var_b;
}Ram7800_SpikeShootingPlant;

/* 152 */
typedef struct Ram7800_MaridiaSpikeyShell {
  uint16 field_0;
  uint16 field_2;
  uint16 field_4;
}Ram7800_MaridiaSpikeyShell;

/* 153 */
typedef struct Ram7800_MiniMaridiaTurtle {
  uint16 var_a;
  uint16 var_b;
  uint16 var_c;
  uint16 var_d;
  uint16 var_e;
  uint16 var_f;
  uint16 var_g;
  uint16 var_h;
}Ram7800_MiniMaridiaTurtle;

/* 154 */
typedef struct Ram7800_ThinHoppingBlobs {
  uint16 var_a;
  uint16 var_b;
  uint16 var_c;
  uint16 var_d;
  uint16 var_e;
  uint16 var_f;
  uint16 var_g;
  uint16 var_h;
}Ram7800_ThinHoppingBlobs;

/* 155 */
typedef struct Ram7800_NorfairLavajumpingEnemy {
  uint16 var_a;
  uint16 var_b;
  uint16 var_c;
  uint16 var_d;
  uint16 var_e;
  uint16 var_f;
  uint16 var_g;
  uint16 var_h;
}Ram7800_NorfairLavajumpingEnemy;

/* 156 */
typedef struct Ram7800_NorfairRio {
  uint16 var_a;
  uint16 var_b;
  uint16 var_c;
  uint16 var_d;
  uint16 var_e;
  uint16 var_f;
  uint16 var_g;
  uint16 var_h;
}Ram7800_NorfairRio;

/* 157 */
typedef struct Ram7800_FireFlea {
  uint16 var_a;
  uint16 var_b;
  uint16 var_c;
}Ram7800_FireFlea;

/* 145 */
typedef union ExtraEnemyRam7800 {
  Ram7800_Kraid kraid;
  uint8 pad[64];
}ExtraEnemyRam7800;

/* 146 */
typedef union ExtraEnemyRam8000 {
  uint8 pad[64];
}ExtraEnemyRam8000;

/* 147 */
typedef struct ExtraEnemyRam8800 {
  uint8 pad[64];
}ExtraEnemyRam8800;

/* 149 */
typedef union Ram3000 {
  uint16 pause_menu_map_tilemap[1024];
  uint16 cinematic_bg_tilemap[1024];
  Ram3000_MsgBox msgbox;
  uint8 msgbox_y_scroll_hdma[240];
  Ram3000_Misc misc;
  Ram3000_Menu menu;
} Ram3000;

/* 150 */
typedef struct OptionsEntry {
  VoidP func_ptr;
  VoidP field_2;
  VoidP field_4;
} OptionsEntry;

typedef struct Ram7800_Default {
  uint16 var_00;
  uint16 var_01;
  uint16 var_02;
  uint16 var_03;
  uint16 var_04;
  uint16 var_05;
  uint16 var_06;
  uint16 var_07;
  uint16 var_08;
  uint16 var_09;
  uint16 var_0A;
  uint16 var_0B;
  uint16 var_0C;
  uint16 var_0D;
  uint16 var_0E;
  uint16 var_0F;
  uint16 var_10;
  uint16 var_11;
  uint16 var_12;
  uint16 var_13;
  uint16 var_14;
  uint16 var_15;
  uint16 var_16;
  uint16 var_17;
  uint16 var_18;
  uint16 var_19;
  uint16 var_1A;
  uint16 var_1B;
  uint16 var_1C;
  uint16 var_1D;
  uint16 var_1E;
  uint16 var_1F;
} Ram7800_Default;


enum Consts_60 {
  addr_unk_604800 = 0x4800,
  addr_unk_604C00 = 0x4C00,
  addr_unk_605000 = 0x5000,
  addr_unk_6053E0 = 0x53E0,
  addr_unk_605400 = 0x5400,
  addr_unk_605800 = 0x5800,
  addr_unk_605820 = 0x5820,
  addr_unk_605880 = 0x5880,
  addr_unk_6059A0 = 0x59A0,
  addr_unk_605BE0 = 0x5BE0,
  addr_unk_6061F0 = 0x61F0,
  addr_unk_606300 = 0x6300,
};
enum Consts_80 {
  addr_kHudTilemaps_AutoReserve = 0x998B,
  addr_kHudTilemaps_Missiles = 0x99A3,
  addrl_kDigitTilesetsHealth = 0x809DBF,
  addrl_kDigitTilesetsWeapon = 0x809DD3,
  addr_word_80A060 = 0xA060,
};
enum Consts_81 {
  addr_kMenuTilemap_GameOver = 0x92DC,
  addr_kMenuTilemap_FindMetroidLarva = 0x9304,
  addr_kMenuTilemap_TryAgain = 0x9334,
  addr_kMenuTilemap_YesReturnToGame = 0x934C,
  addr_kMenuTilemap_NoGoToTitle = 0x93A0,
  addr_kLeftMapScrollArrowData = 0xAF32,
  addr_kRightMapScrollArrowData = 0xAF3C,
  addr_kUpMapScrollArrowData = 0xAF46,
  addr_kDownMapScrollArrowData = 0xAF50,
  addr_kMenuTilemap_SamusData = 0xB40A,
  addr_kMenuTilemap_SamusA = 0xB436,
  addr_kMenuTilemap_SamusB = 0xB456,
  addr_kMenuTilemap_SamusC = 0xB476,
  addr_kMenuTilemap_Energy = 0xB496,
  addr_kMenuTilemap_TIME = 0xB4A0,
  addr_word_81B4A8 = 0xB4A8,
  addr_kMenuTilemap_NoData = 0xB4AC,
  addr_kMenuTilemap_DataCopy = 0xB4C4,
  addr_kMenuTilemap_DataClear = 0xB4D8,
  addr_kMenuTilemap_Exit = 0xB4EE,
  addr_kMenuTilemap_DataCopyMode = 0xB4F8,
  addr_kMenuTilemap_DataClearMode = 0xB534,
  addr_kMenuTilemap_CopyWhichData = 0xB574,
  addr_kMenuTilemap_CopySamusToWhere = 0xB596,
  addr_kMenuTilemap_CopySamusToSamus = 0xB5C8,
  addr_kMenuTilemap_IsThisOk = 0xB602,
  addr_kMenuTilemap_Yes = 0xB61A,
  addr_kMenuTilemap_No = 0xB62A,
  addr_kMenuTilemap_CopyCompleted = 0xB63A,
  addr_kMenuTilemap_ClearWhichData = 0xB65A,
  addr_kMenuTilemap_ClearSamusA = 0xB69A,
  addr_kMenuTilemap_DataCleared = 0xB6DA,
  addr_kAreaSelectForegroundTilemap = 0xB71A,
  addr_kAreaSelectBackgroundTilemaps = 0xBF1A,
};
enum Consts_82 {
  addr_kPauseMenuMapData = 0x9717,
  addr_stru_82B9A0 = 0xB9A0,
  addr_stru_82B9AA = 0xB9AA,
  addr_stru_82B9B4 = 0xB9B4,
  addr_stru_82B9BE = 0xB9BE,
  addr_kgameOverBabyMetridInstructionList = 0xBC27,
  addr_kEquipmentScreenTilemap_MANUAL = 0xBF22,
  addr_kEquipmentScreenTilemap_AUTO = 0xBF2A,
  addr_kEquipmentScreenTilemap_Blank = 0xC01A,
  addr_kEquipmentTilemapOffs_Tanks = 0xC068,
  addr_kEquipmentTilemapOffs_Weapons = 0xC06C,
  addr_kEquipmentTilemapOffs_Suits = 0xC076,
  addr_kEquipmentTilemapOffs_Boots = 0xC082,
  addr_kDummySamusWireframeTilemap = 0xC639,
  addr_kMapIconDataPointers = 0xC7CB,
  addr_off_82F4B6 = 0xF4B6,
  addr_stru_82F4B8 = 0xF4B8,
  addr_stru_82F4C4 = 0xF4C4,
  addr_stru_82F4CA = 0xF4CA,
  addr_stru_82F4D0 = 0xF4D0,
  addr_stru_82F4D6 = 0xF4D6,
};
enum Consts_83 {
  addr_kDoorDef_947a = 0x947A,
};
enum Consts_84 {
  addr_PlmPreInstr_Empty4 = 0x8AA6,
  addr_locret_848AE0 = 0x8AE0,
  addr_kDefaultPlmDrawInstruction = 0x8DA0,
  addr_word_84AD76 = 0xAD76,
  addr_kPlmHeader_B6FF = 0xB6FF,
  addr_locret_84BB6A = 0xBB6A,
  addr_locret_84BBDC = 0xBBDC,
  addr_kPlmInstrList_C91C = 0xC91C,
  addr_kPlmInstrList_C922 = 0xC922,
  addr_kPlmHeader_D113 = 0xD113,
  addr_kPlmHeader_D6EA = 0xD6EA,
  addr_locret_84D779 = 0xD779,
};
enum Consts_86 {
  addr_stru_868BC2 = 0x8BC2,
  addr_stru_868BD0 = 0x8BD0,
  addr_stru_868BDE = 0x8BDE,
  addr_stru_868BEC = 0x8BEC,
  addr_stru_868BFA = 0x8BFA,
  addr_stru_868C08 = 0x8C08,
  addr_stru_868C16 = 0x8C16,
  addr_stru_868C24 = 0x8C24,
  addr_stru_868E50 = 0x8E50,
  addr_stru_868E5E = 0x8E5E,
  addr_word_868EDF = 0x8EDF,
  addr_stru_868F8F = 0x8F8F,
  addr_stru_868F9D = 0x8F9D,
  addr_kEproj_CrocomireSpikeWallPieces = 0x90C1,
  addr_kRidleysFireball_Tab0 = 0x9408,
  addr_off_869574 = 0x9574,
  addr_stru_869634 = 0x9634,
  addr_stru_869650 = 0x9650,
  addr_stru_86966C = 0x966C,
  addr_stru_86967A = 0x967A,
  addr_stru_869688 = 0x9688,
  addr_stru_869696 = 0x9696,
  addr_stru_869734 = 0x9734,
  addr_stru_869742 = 0x9742,
  addr_word_86976C = 0x976C,
  addr_word_869772 = 0x9772,
  addr_word_869782 = 0x9782,
  addr_word_8697AC = 0x97AC,
  addr_off_8697B4 = 0x97B4,
  addr_off_8697F8 = 0x97F8,
  addr_kEproj_DestroyableFireballs = 0x9C29,
  addr_kEproj_StartingFireballs = 0x9C37,
  addr_kEproj_RocksKraidSpits = 0x9C45,
  addr_kEproj_RocksFallingKraidCeiling = 0x9C53,
  addr_kEproj_RocksWhenKraidRisesLeft = 0x9C61,
  addr_kEproj_RocksWhenKraidRisesRight = 0x9C6F,
  addr_kEproj_MiniKraidSpit = 0x9DB0,
  addr_kEproj_MiniKraidSpikesLeft = 0x9DBE,
  addr_kEproj_MiniKraidSpikesRight = 0x9DCC,
  addr_word_869F41 = 0x9F41,
  addr_word_869F7D = 0x9F7D,
  addr_off_869FB9 = 0x9FB9,
  addr_off_869FE1 = 0x9FE1,
  addr_stru_86A17B = 0xA17B,
  addr_kEproj_PirateClaw = 0xA189,
  addr_off_86A28B = 0xA28B,
  addr_stru_86A379 = 0xA379,
  addr_kEproj_CeresElevatorPad = 0xA387,
  addr_kEproj_CeresElevatorPlatform = 0xA395,
  addr_kEproj_PrePhantomRoom = 0xA3B0,
  addr_stru_86A95B = 0xA95B,
  addr_kEproj_BombTorizoLowHealthInitialDrool = 0xA969,
  addr_kEproj_BombTorizoExplosiveSwipe = 0xA985,
  addr_kEproj_BombTorizoLowHealthExplode = 0xA9A1,
  addr_kEproj_BombTorizoDeathExplosion = 0xA9AF,
  addr_kEprojInit_AB07_Tile0 = 0xA9BD,
  addr_kEprojInit_AB07_Tile1 = 0xA9FD,
  addr_off_86AB25 = 0xAB25,
  addr_off_86AB41 = 0xAB41,
  addr_kEprojInit_BombTorizosChozoOrbs_init0 = 0xAC08,
  addr_kEprojInit_BombTorizosChozoOrbs_init1 = 0xAC12,
  addr_kEprojInit_GoldenTorizosChozoOrbs_init0 = 0xAC99,
  addr_kEprojInit_GoldenTorizosChozoOrbs_init1 = 0xACA3,
  addr_kEproj_BombTorizosChozoOrbs = 0xAD5E,
  addr_kEproj_GoldenTorizosChozoOrbs = 0xAD7A,
  addr_off_86ADBF = 0xADBF,
  addr_off_86ADD2 = 0xADD2,
  addr_off_86ADE5 = 0xADE5,
  addr_kEproj_BombTorizoSonicBoom = 0xAEA8,
  addr_kEproj_GoldenTorizoSonicBoom = 0xAEB6,
  addr_kEproj_WreckedShipChozoSpikeFootsteps_1 = 0xAF68,
  addr_kEproj_TourianStatueDustClouds = 0xAF84,
  addr_kEproj_TourianLandingDustCloudsRightFoot = 0xAFE5,
  addr_stru_86AFF3 = 0xAFF3,
  addr_kEprojInit_GoldenTorizoEgg0 = 0xB02F,
  addr_kEprojInit_GoldenTorizoEgg1 = 0xB039,
  addr_off_86B14B = 0xB14B,
  addr_off_86B166 = 0xB166,
  addr_off_86B190 = 0xB190,
  addr_off_86B1A8 = 0xB1A8,
  addr_stru_86B1C0 = 0xB1C0,
  addr_off_86B2EF = 0xB2EF,
  addr_kEproj_GoldenTorizoSuperMissile = 0xB31A,
  addr_stru_86B376 = 0xB376,
  addr_stru_86B380 = 0xB380,
  addr_off_86B3CD = 0xB3CD,
  addr_off_86B3E5 = 0xB3E5,
  addr_kEproj_GoldenTorizoEyeBeam = 0xB428,
  addr_word_86B4BF = 0xB4BF,
  addr_word_86B4CB = 0xB4CB,
  addr_word_86B4D7 = 0xB4D7,
  addr_word_86B4E3 = 0xB4E3,
  addr_kEproj_LavaSeahorseFireball = 0xB5CB,
  addr_off_86B5F3 = 0xB5F3,
  addr_off_86B61D = 0xB61D,
  addr_kEproj_EyeDoorProjectile = 0xB743,
  addr_kEproj_EyeDoorSweat = 0xB751,
  addr_off_86B79F = 0xB79F,
  addr_stru_86BA5C = 0xBA5C,
  addr_kEproj_TourianStatueEyeGlow = 0xBA6A,
  addr_kEproj_TourianStatueUnlockingParticle = 0xBA78,
  addr_kEproj_TourianStatueUnlockingParticleTail = 0xBA86,
  addr_kEproj_TourianStatueSoul = 0xBA94,
  addr_kEproj_TourianStatueRidley = 0xBAA2,
  addr_kEproj_TourianStatuePhantoon = 0xBAB0,
  addr_kEproj_TourianStatueBaseDecoration = 0xBABE,
  addr_kEproj_NuclearWaffleBody = 0xBBC7,
  addr_word_86BBD5 = 0xBBD5,
  addr_stru_86BD5A = 0xBD5A,
  addr_kEproj_ShaktoolAttackFrontCircle = 0xBE25,
  addr_kEproj_ShaktoolAttackMiddleCircle = 0xBE33,
  addr_kEproj_ShaktoolAttackBackCircle = 0xBE41,
  addr_kEproj_MotherBrainRoomTurrets = 0xC17E,
  addr_kEproj_MotherBrainRoomTurretBullets = 0xC18C,
  addr_off_86C8E1 = 0xC8E1,
  addr_kEproj_MotherBrainDeathExplosion = 0xCB13,
  addr_kEproj_MotherBrainExplodedEscapeDoor = 0xCB21,
  addr_kEproj_MotherBrainPurpleBreathBig = 0xCB2F,
  addr_kEproj_MotherBrainPurpleBreathSmall = 0xCB3D,
  addr_kEproj_MotherBrainBlueRingLasers = 0xCB4B,
  addr_kEproj_MotherBrainBomb = 0xCB59,
  addr_kEproj_MotherBrainDeathBeamCharging = 0xCB67,
  addr_kEproj_MotherBrainDeathBeamFired = 0xCB75,
  addr_kEproj_MotherBrainRainbowBeamCharging = 0xCB83,
  addr_kEproj_MotherBrainDrool = 0xCB91,
  addr_kEproj_MotherBrainDyingDrool = 0xCB9F,
  addr_kEproj_MotherBrainRainbowBeamExplosion = 0xCBAD,
  addr_kEproj_TimeBombSetJapaneseText = 0xCBBB,
  addr_kEproj_MotherBrainTubeFalling_TopLeft = 0xCC69,
  addr_kEproj_MotherBrainTubeFalling_TopMiddleLeft = 0xCC77,
  addr_kEproj_MotherBrainTubeFalling_TopMiddleRight = 0xCC85,
  addr_kEproj_MotherBrainGlassShatteringSparkle = 0xCF0A,
  addr_off_86CF56 = 0xCF56,
  addr_word_86D03C = 0xD03C,
  addr_word_86D04A = 0xD04A,
  addr_word_86D052 = 0xD052,
  addr_off_86D218 = 0xD218,
  addr_kEproj_MaridiaFloatersSpikes = 0xD298,
  addr_kEproj_WreckedShipRobotLaserUpLeft = 0xD2A6,
  addr_kEproj_WreckedShipRobotLaserHorizontal = 0xD2B4,
  addr_kEproj_WreckedShipRobotLaserDownLeft = 0xD2C2,
  addr_kEproj_WreckedShipRobotLaserUpRight = 0xD2D0,
  addr_kEproj_WreckedShipRobotLaserDownRight = 0xD2DE,
  addr_kEproj_N00bTubeShards = 0xD912,
  addr_kEproj_N00bTubeReleasedAirBubbles = 0xD920,
  addr_kEproj_SpikeShootingPlantSpikes = 0xDAFE,
  addr_word_86DB0C = 0xDB0C,
  addr_Eproj_DBF2 = 0xDBF2,
  addr_word_86DC06 = 0xDC06,
  addr_kEproj_SporeSpawnsStalk = 0xDE6C,
  addr_kEproj_Spores = 0xDE7A,
  addr_kEproj_SporeSpawners = 0xDE88,
  addr_word_86DE96 = 0xDE96,
  addr_word_86DEA6 = 0xDEA6,
  addr_stru_86DFBC = 0xDFBC,
  addr_stru_86DFCA = 0xDFCA,
  addr_word_86DFD8 = 0xDFD8,
  addr_word_86DFDE = 0xDFDE,
  addr_kEproj_LavaThrownByLavaman = 0xE0E0,
  addr_word_86E208 = 0xE208,
  addr_kEproj_DustCloudExplosion = 0xE509,
  addr_kEproj_EyeDoorSmoke = 0xE517,
  addr_kEproj_SaveStationElectricity = 0xE6D2,
  addr_kEproj_BotwoonsBody = 0xEBA0,
  addr_word_86EBAE = 0xEBAE,
  addr_kEproj_BotwoonsSpit = 0xEC48,
  addr_word_86EC56 = 0xEC56,
  addr_word_86EC5C = 0xEC5C,
  addr_kEproj_YappingMawsBody = 0xEC95,
  addr_word_86ECA3 = 0xECA3,
  addr_kEproj_Pickup = 0xF337,
  addr_kEproj_EnemyDeathExplosion = 0xF345,
  addr_kEproj_Sparks = 0xF498,
};
enum Consts_87 {
  addr_kAnimtiles_WreckedShipTradmillRight = 0x8275,
  addr_kAnimtiles_WreckedShipTradmillLeft = 0x827B,
  addr_kAnimtiles_Lava = 0x82AB,
  addr_kAnimtiles_Acid = 0x82C9,
  addr_kAnimtiles_Rain = 0x82E7,
  addr_kAnimtiles_Spores = 0x82FD,
  addr_kAnimtiles_TourianStatue_Phantoon = 0x854C,
  addr_kAnimtiles_TourianStatue_Ridley = 0x8552,
  addr_kAnimtiles_TourianStatue_Kraid = 0x8558,
  addr_kAnimtiles_TourianStatue_Draygon = 0x855E,
};
enum Consts_88 {
  addr_locret_88858A = 0x858A,
  addr_loc_889180 = 0x9180,
  addr_kPowerBombExplosionShapeDef0 = 0x9246,
  addr_byte_889F06 = 0x9F06,
  addr_word_88A8E8 = 0xA8E8,
  addr_word_88A8E8__plus__2 = 0xA8EA,
  addr_word_88A8E8__plus__4 = 0xA8EC,
  addr_word_88A8E8__plus__6 = 0xA8EE,
  addr_off_88AD9C = 0xAD9C,
  addr_off_88ADA6 = 0xADA6,
  addr_word_88DF5F = 0xDF5F,
  addr_word_88DF65 = 0xDF65,
  addr_word_88DF6B = 0xDF6B,
  addr_word_88DF71 = 0xDF71,
};
enum Consts_89 {
  addr_kIndirectHdmaTable_PowerBombExplodeLeft = 0x9800,
  addr_kIndirectHdmaTable_PowerBombExplodeRight = 0xA101,
};
enum Consts_8B {
  addr_kCinematicSpriteObjectDef_8BA0EF = 0xA0EF,
  addr_kCinematicSpriteObjectDef_8BA0F5 = 0xA0F5,
  addr_kCinematicSpriteObjectDef_8BA0FB = 0xA0FB,
  addr_kCinematicSpriteObjectDef_8BA101 = 0xA101,
  addr_kCinematicSpriteObjectDef_8BA107 = 0xA107,
  addr_kCinematicSpriteObjectDef_8BA113 = 0xA113,
  addr_kCinematicSpriteObjectDef_8BA119 = 0xA119,
  addr_kCinematicSpriteObjectDef_8BA125 = 0xA125,
  addr_kMode7ObjBabyMetroidInTitle = 0xA355,
  addr_kCinematicFunction_Intro_Func56_M7 = 0xBE74,
  addr_kCinematicFunction_Intro_Func76_M7_0 = 0xC3E6,
  addr_kCinematicFunction_Intro_Func76_M7_1 = 0xC3F0,
  addr_kCinematicFunction_Intro_Func76_M7_2 = 0xC3FA,
  addr_off_8BCB19 = 0xCB19,
  addr_word_8BCB3B = 0xCB3B,
  addr_word_8BCBFB = 0xCBFB,
  addr_unk_8BCC03 = 0xCC03,
  addr_word_8BCC23 = 0xCC23,
  addr_word_8BCD71 = 0xCD71,
  addr_off_8BCE53 = 0xCE53,
  addr_kCinematicSpriteObjectDef_8BCE55 = 0xCE55,
  addr_kCinematicSpriteObjectDef_8BCE5B = 0xCE5B,
  addr_kCinematicSpriteObjectDef_8BCE61 = 0xCE61,
  addr_kCinematicSpriteObjectDef_8BCE67 = 0xCE67,
  addr_kCinematicSpriteObjectDef_8BCE6D = 0xCE6D,
  addr_kCinematicSpriteObjectDef_8BCE73 = 0xCE73,
  addr_kCinematicSpriteObjectDef_8BCE79 = 0xCE79,
  addr_kCinematicSpriteObjectDef_8BCE7F = 0xCE7F,
  addr_kCinematicSpriteObjectDef_8BCE85 = 0xCE85,
  addr_kCinematicSpriteObjectDef_8BCE8B = 0xCE8B,
  addr_kCinematicSpriteObjectDef_8BCE91 = 0xCE91,
  addr_kCinematicSpriteObjectDef_8BCEA3 = 0xCEA3,
  addr_kCinematicSpriteObjectDef_8BCEAF = 0xCEAF,
  addr_kCinematicSpriteObjectDef_8BCEB5 = 0xCEB5,
  addr_kCinematicSpriteObjectDef_8BCEBB = 0xCEBB,
  addr_kCinematicSpriteObjectDef_8BCEC1 = 0xCEC1,
  addr_kCinematicSpriteObjectDef_8BCEC7 = 0xCEC7,
  addr_kCinematicSpriteObjectDef_8BCECD = 0xCECD,
  addr_kCinematicSpriteObjectDef_8BCED3 = 0xCED3,
  addr_kCinematicSpriteObjectDef_8BCED9 = 0xCED9,
  addr_kCinematicSpriteObjectDef_8BCEDF = 0xCEDF,
  addr_kCinematicSpriteObjectDef_8BCEE5 = 0xCEE5,
  addr_kCinematicSpriteObjectDef_8BCEEB = 0xCEEB,
  addr_kCinematicSpriteObjectDef_8BCEF1 = 0xCEF1,
  addr_kCinematicSpriteObjectDef_8BCEF7 = 0xCEF7,
  addr_kCinematicSpriteObjectDef_8BCEFD = 0xCEFD,
  addr_kCinematicSpriteObjectDef_8BCF03 = 0xCF03,
  addr_kCinematicSpriteObjectDef_8BCF09 = 0xCF09,
  addr_kCinematicSpriteObjectDef_8BCF0F = 0xCF0F,
  addr_kCinematicSpriteObjectDef_8BCF15 = 0xCF15,
  addr_kCinematicSpriteObjectDef_8BCF1B = 0xCF1B,
  addr_kCinematicSpriteObjectDef_8BCF21 = 0xCF21,
  addr_kCinematicSpriteObjectDef_8BCF27 = 0xCF27,
  addr_kCinematicSpriteObjectDef_8BCF2D = 0xCF2D,
  addr_kCinematicSpriteObjectDef_8BCF33 = 0xCF33,
  addr_kCinematicSpriteObjectDef_8BCF39 = 0xCF39,
  addr_kCinematicBgObjectDef_8BCF3F = 0xCF3F,
  addr_kCinematicBgObjectDef_8BCF45 = 0xCF45,
  addr_kCinematicBgObjectDef_8BCF4B = 0xCF4B,
  addr_kCinematicBgObjectDef_8BCF51 = 0xCF51,
  addr_kCinematicBgObjectDef_8BCF57 = 0xCF57,
  addr_kCinematicBgObjectDef_8BCF5D = 0xCF5D,
  addr_kCinematicBgObjectDef_8BCF63 = 0xCF63,
  addr_kCinematicBgObjectDef_8BCF69 = 0xCF69,
  addr_word_8BCF75 = 0xCF75,
  addr_word_8BCFBD = 0xCFBD,
  addr_word_8BCFFD = 0xCFFD,
  addr_word_8BD055 = 0xD055,
  addr_word_8BD085 = 0xD085,
  addr_word_8BD0E1 = 0xD0E1,
  addr_word_8BD0F9 = 0xD0F9,
  addr_word_8BD15D = 0xD15D,
  addr_word_8BD1B9 = 0xD1B9,
  addr_word_8BD215 = 0xD215,
  addr_word_8BD259 = 0xD259,
  addr_word_8BD2A5 = 0xD2A5,
  addr_word_8BD2D5 = 0xD2D5,
  addr_word_8BD30D = 0xD30D,
  addr_word_8BD371 = 0xD371,
  addr_word_8BD389 = 0xD389,
  addr_off_8BD3E7 = 0xD3E7,
  addr_kMode7ObjectDef_8BD401 = 0xD401,
  addr_kMode7ObjectDef_8BD407 = 0xD407,
  addr_kMode7ObjectDef_8BD40D = 0xD40D,
  addr_kMode7ObjectDef_8BD413 = 0xD413,
  addr_kMode7ObjectDef_8BD419 = 0xD419,
  addr_kMode7ObjectDef_8BD41F = 0xD41F,
  addr_kMode7ObjectDef_8BD425 = 0xD425,
  addr_kMode7ObjectDef_8BD42B = 0xD42B,
  addr_kMode7ObjectDef_8BD431 = 0xD431,
  addr_kMode7ObjectDef_8BD437 = 0xD437,
  addr_loc_8BE1B4 = 0xE1B4,
  addr_word_8BED95 = 0xED95,
  addr_word_8BED9D = 0xED9D,
  addr_off_8BEE9B = 0xEE9B,
  addr_kCinematicSpriteObjectDef_8BEE9D = 0xEE9D,
  addr_kCinematicSpriteObjectDef_8BEEA3 = 0xEEA3,
  addr_kCinematicSpriteObjectDef_8BEEA9 = 0xEEA9,
  addr_kCinematicSpriteObjectDef_8BEEAF = 0xEEAF,
  addr_kCinematicSpriteObjectDef_8BEEB5 = 0xEEB5,
  addr_kCinematicSpriteObjectDef_8BEEBB = 0xEEBB,
  addr_kCinematicSpriteObjectDef_8BEEC1 = 0xEEC1,
  addr_kCinematicSpriteObjectDef_8BEEC7 = 0xEEC7,
  addr_kCinematicSpriteObjectDef_8BEECD = 0xEECD,
  addr_kCinematicSpriteObjectDef_8BEED3 = 0xEED3,
  addr_kCinematicSpriteObjectDef_8BEED9 = 0xEED9,
  addr_kCinematicSpriteObjectDef_8BEEDF = 0xEEDF,
  addr_kCinematicSpriteObjectDef_8BEEE5 = 0xEEE5,
  addr_kCinematicSpriteObjectDef_8BEEEB = 0xEEEB,
  addr_kCinematicSpriteObjectDef_8BEEF1 = 0xEEF1,
  addr_kCinematicSpriteObjectDef_8BEEF7 = 0xEEF7,
  addr_kCinematicSpriteObjectDef_8BEEFD = 0xEEFD,
  addr_kCinematicSpriteObjectDef_8BEF03 = 0xEF03,
  addr_kCinematicSpriteObjectDef_8BEF09 = 0xEF09,
  addr_kCinematicSpriteObjectDef_8BEF0F = 0xEF0F,
  addr_kCinematicSpriteObjectDef_8BEF15 = 0xEF15,
  addr_kCinematicSpriteObjectDef_8BEF1B = 0xEF1B,
  addr_kCinematicSpriteObjectDef_8BEF27 = 0xEF27,
  addr_kCinematicSpriteObjectDef_8BEF2D = 0xEF2D,
  addr_kCinematicSpriteObjectDef_8BEF33 = 0xEF33,
  addr_kCinematicSpriteObjectDef_8BEF39 = 0xEF39,
  addr_kCinematicSpriteObjectDef_8BEF3F = 0xEF3F,
  addr_kCinematicSpriteObjectDef_8BEF45 = 0xEF45,
  addr_kCinematicSpriteObjectDef_8BEF4B = 0xEF4B,
  addr_kCinematicSpriteObjectDef_8BEF51 = 0xEF51,
  addr_kCinematicSpriteObjectDef_8BEF57 = 0xEF57,
  addr_kCinematicSpriteObjectDef_8BEF5D = 0xEF5D,
  addr_kCinematicSpriteObjectDef_8BEF63 = 0xEF63,
  addr_kCinematicSpriteObjectDef_8BEF69 = 0xEF69,
  addr_kCinematicSpriteObjectDef_8BEF6F = 0xEF6F,
  addr_kCinematicSpriteObjectDef_8BEF75 = 0xEF75,
  addr_kCinematicSpriteObjectDef_8BEF7B = 0xEF7B,
  addr_kCinematicSpriteObjectDef_8BEF81 = 0xEF81,
  addr_kCinematicSpriteObjectDef_8BEF87 = 0xEF87,
  addr_kCinematicSpriteObjectDef_8BEF8D = 0xEF8D,
  addr_kCinematicSpriteObjectDef_8BEF93 = 0xEF93,
  addr_stru_8BF6F8 = 0xF6F8,
  addr_kCinematicBgObjectDef_8BF748 = 0xF748,
  addr_kCinematicBgObjectDef_8BF74E = 0xF74E,
};
enum Consts_8C {
  addr_kSpriteMap_NintendoLogo = 0x80BB,
};
enum Consts_8D {
  addr_locret_8DC5E3 = 0xC5E3,
  addr_off_8DE192 = 0xE192,
  addr_kPalfx_E194 = 0xE194,
  addr_kPalfx_E198 = 0xE198,
  addr_kPalfx_E19C = 0xE19C,
  addr_kPalfx_E1A0 = 0xE1A0,
  addr_kPalfx_E1A4 = 0xE1A4,
  addr_kPalfx_E1A8 = 0xE1A8,
  addr_kPalfx_E1AC = 0xE1AC,
  addr_kPalfx_E1B0 = 0xE1B0,
  addr_kPalfx_E1B8 = 0xE1B8,
  addr_kPalfx_E1BC = 0xE1BC,
  addr_stru_8DE1C0 = 0xE1C0,
  addr_kPalfx_E1C4 = 0xE1C4,
  addr_kPalfx_E1C8 = 0xE1C8,
  addr_kPalfx_E1CC = 0xE1CC,
  addr_kPalfx_E1D0 = 0xE1D0,
  addr_kPalfx_E1D4 = 0xE1D4,
  addr_kPalfx_E1D8 = 0xE1D8,
  addr_kPalfx_E1DC = 0xE1DC,
  addr_kPalfx_E1E0 = 0xE1E0,
  addr_kPalfx_E1E4 = 0xE1E4,
  addr_kPalfx_E1E8 = 0xE1E8,
  addr_stru_8DE1F0 = 0xE1F0,
  addr_stru_8DE1F4 = 0xE1F4,
  addr_stru_8DE1F8 = 0xE1F8,
  addr_stru_8DE1FC = 0xE1FC,
  addr_kPalfx_E200 = 0xE200,
  addr_off_8DE3E0 = 0xE3E0,
  addr_off_8DE400 = 0xE400,
  addr_off_8DE420 = 0xE420,
  addr_kPalfxInstrList_E45E = 0xE45E,
  addr_off_8DE68A = 0xE68A,
  addr_off_8DE8B6 = 0xE8B6,
  addr_word_8DEB43 = 0xEB43,
  addr_word_8DEC76 = 0xEC76,
  addr_stru_8DF759 = 0xF759,
  addr_stru_8DF75D = 0xF75D,
  addr_kPalfx_FFC9 = 0xFFC9,
  addr_kPalfx_FFCD = 0xFFCD,
  addr_kPalfx_FFD1 = 0xFFD1,
  addr_kPalfx_FFD5 = 0xFFD5,
};
enum Consts_8F {
  addr_kRoom_96ba = 0x96BA,
  addr_kRoom_9804 = 0x9804,
  addr_kRoom_a66a = 0xA66A,
  addr_kRoom_b32e = 0xB32E,
  addr_kRoom_b457 = 0xB457,
  addr_kRoom_cefb = 0xCEFB,
  addr_kRoom_dd58 = 0xDD58,
  addr_kRoom_dede = 0xDEDE,
  addr_kDoorClosingPlmIds = 0xE68A,
};
enum Consts_90 {
  addr_loc_908029 = 0x8029,
  addr_stru_909F25 = 0x9F25,
  addr_stru_909F31 = 0x9F31,
  addr_stru_909F3D = 0x9F3D,
  addr_kSamusSpeedTable_Normal_X = 0x9F49,
  addr_kSamusSpeedTable_Normal_X__plus__12 = 0x9F55,
  addr_kSamusSpeedTable_Water_X = 0xA08D,
  addr_kSamusSpeedTable_LavaAcid_X = 0xA1DD,
  addr_kSuperMissileAccelerations = 0xc303,
  addr_kSuperMissileAccelerations2 = 0xc32b,
  addr_loc_90C4F0 = 0xC4F0,
};
enum Consts_91 {
  addr_off_91864B = 0x864B,
  addr_kDemoInstrs_LeaveDemo = 0x8776,
  addr_stru_91877E = 0x877E,
  addr_stru_918784 = 0x8784,
  addr_stru_919346 = 0x9346,
};
enum Consts_94 {
  addr_word_94B18B = 0xB18B,
  addr_word_94B18F = 0xB18F,
  addr_word_94B193 = 0xB193,
  addr_word_94B197 = 0xB197,
};
enum Consts_9B {
  addr_kSamusPalette_PowerSuit = 0x9400,
  addr_kSamusPalette_VariaSuit = 0x9520,
  addr_kSamusPalette_GravitySuit = 0x9800,
  addr_word_9BA120 = 0xA120,
  addr_word_9BA380 = 0xA380,
  addr_word_9BA3A0 = 0xA3A0,

};
enum Consts_A0 {
  addr_kSpritemap_Nothing_A0 = 0x804D,
  addr_kExtendedSpritemap_Nothing_A0 = 0x804F,
  addr_kEnemyDef_DAFF = 0xDAFF,
  addr_kEnemyDef_DD7F = 0xDD7F,
  addr_kEnemyDef_DDBF = 0xDDBF,
  addr_kEnemyDef_DE3F = 0xDE3F,
  addr_kEnemyDef_DE7F = 0xDE7F,
  addr_kEnemyDef_DF3F = 0xDF3F,
  addr_kEnemyDef_DF7F = 0xDF7F,
  addr_kEnemyDef_E0FF = 0xE0FF,
  addr_kEnemyDef_E17F = 0xE17F,
  addr_kEnemyDef_E2BF = 0xE2BF,
  addr_kEnemyDef_E4BF = 0xE4BF,
  addr_kEnemyDef_E4FF = 0xE4FF,
  addr_kEnemyDef_E7FF = 0xE7FF,
  addr_kEnemyDef_E83F = 0xE83F,
  addr_kEnemyDef_EC3F = 0xEC3F,
  addr_kEnemyDef_EEFF = 0xEEFF,
  addr_kEnemyDef_F293 = 0xF293,
  addr_kEnemyDef_F353 = 0xF353,
  addr_kEnemyDef_F593 = 0xF593,
};
enum Consts_A2 {
  addr_kSpritemap_Nothing_A2 = 0x804D,
  addr_kBouncingGoofball_Ilist_86A7 = 0x86A7,
  addr_kBouncingGoofball_Ilist_86BF = 0x86BF,
  addr_kMiniCrocomire_Ilist_8932 = 0x8932,
  addr_kMiniCrocomire_Ilist_8948 = 0x8948,
  addr_kMiniCrocomire_Ilist_8958 = 0x8958,
  addr_kMiniCrocomire_Ilist_896E = 0x896E,
  addr_kMaridiaBeybladeTurtle_Ilist_8B80 = 0x8B80,
  addr_kMaridiaBeybladeTurtle_Ilist_8BD2 = 0x8BD2,
  addr_kMaridiaBeybladeTurtle_Ilist_8C02 = 0x8C02,
  addr_kMaridiaBeybladeTurtle_Ilist_8C1C = 0x8C1C,
  addr_kMaridiaBeybladeTurtle_Ilist_8C30 = 0x8C30,
  addr_kMaridiaBeybladeTurtle_Ilist_8C44 = 0x8C44,
  addr_kMaridiaBeybladeTurtle_Ilist_8C4A = 0x8C4A,
  addr_kMaridiaBeybladeTurtle_Ilist_8C62 = 0x8C62,
  addr_kMaridiaBeybladeTurtle_Ilist_8C72 = 0x8C72,
  addr_kMaridiaBeybladeTurtle_Ilist_8D00 = 0x8D00,
  addr_kMaridiaBeybladeTurtle_Ilist_8D14 = 0x8D14,
  addr_kMaridiaBeybladeTurtle_Ilist_8D28 = 0x8D28,
  addr_kMaridiaBeybladeTurtle_Ilist_8D40 = 0x8D40,
  addr_locret_A28E09 = 0x8E09,
  addr_kThinHoppingBlobs_Ilist_99AD = 0x99AD,
  addr_kThinHoppingBlobs_Ilist_99C1 = 0x99C1,
  addr_kThinHoppingBlobs_Ilist_99D5 = 0x99D5,
  addr_kThinHoppingBlobs_Ilist_99E9 = 0x99E9,
  addr_kThinHoppingBlobs_Ilist_99EF = 0x99EF,
  addr_kThinHoppingBlobs_Ilist_99F5 = 0x99F5,
  addr_kThinHoppingBlobs_Ilist_99FB = 0x99FB,
  addr_kThinHoppingBlobs_Ilist_9A01 = 0x9A01,
  addr_kSpikeShootingPlant_Ilist_9E8A = 0x9E8A,
  addr_kSpikeShootingPlant_Ilist_9EB0 = 0x9EB0,
  addr_kSpikeShootingPlant_Ilist_9EDA = 0x9EDA,
  addr_kSpikeShootingPlant_Ilist_9F00 = 0x9F00,
  addr_kMaridiaSpikeyShell_Ilist_A3AB = 0xA3AB,
  addr_kMaridiaSpikeyShell_Ilist_A3BD = 0xA3BD,
  addr_kGunshipTop_Ilist_A5BE = 0xA5BE,
  addr_kGunshipTop_Ilist_A5EE = 0xA5EE,
  addr_kGunshipTop_Ilist_A60E = 0xA60E,
  addr_kGunshipTop_Ilist_A616 = 0xA616,
  addr_kGunshipTop_Ilist_A61C = 0xA61C,
  addr_kFlies_Ilist_B013 = 0xB013,
  addr_kNorfairErraticFireball_Ilist_B2DC = 0xB2DC,
  addr_kNorfairErraticFireball_Ilist_B51A = 0xB51A,
  addr_kRinka_Ilist_B9E0 = 0xB9E0,
  addr_kRinka_Ilist_BA0C = 0xBA0C,
  addr_kRio_Ilist_BB4B = 0xBB4B,
  addr_stru_A2BB53 = 0xBB53,
  addr_kRio_Ilist_BB7F = 0xBB7F,
  addr_kRio_Ilist_BB97 = 0xBB97,
  addr_kRio_Ilist_BBA3 = 0xBBA3,
  addr_kNorfairLavajumpingEnemy_Ilist_BE3C = 0xBE3C,
  addr_kNorfairLavajumpingEnemy_Ilist_BE42 = 0xBE42,
  addr_kNorfairLavajumpingEnemy_Ilist_BE62 = 0xBE62,
  addr_kNorfairRio_Ilist_C0F1 = 0xC0F1,
  addr_kNorfairRio_Ilist_C107 = 0xC107,
  addr_kNorfairRio_Ilist_C12F = 0xC12F,
  addr_kNorfairRio_Ilist_C145 = 0xC145,
  addr_kNorfairRio_Ilist_C179 = 0xC179,
  addr_kNorfairRio_Ilist_C18F = 0xC18F,
  addr_kNorfairRio_Ilist_C1A3 = 0xC1A3,
  addr_kLowerNorfairRio_Ilist_C61A = 0xC61A,
  addr_kLowerNorfairRio_Ilist_C630 = 0xC630,
  addr_kLowerNorfairRio_Ilist_C65A = 0xC65A,
  addr_kLowerNorfairRio_Ilist_C662 = 0xC662,
  addr_kLowerNorfairRio_Ilist_C674 = 0xC674,
  addr_kLowerNorfairRio_Ilist_C686 = 0xC686,
  addr_kLowerNorfairRio_Ilist_C6B0 = 0xC6B0,
  addr_kMaridiaLargeSnail_Ilist_CA4B = 0xCA4B,
  addr_kHirisingSlowfalling_Ilist_D82C = 0xD82C,
  addr_kHirisingSlowfalling_Ilist_D834 = 0xD834,
  addr_kHirisingSlowfalling_Ilist_D840 = 0xD840,
  addr_kGripper_Ilist_E19B = 0xE19B,
  addr_kGripper_Ilist_E1AF = 0xE1AF,
  addr_kRipper_Ilist_E2E0 = 0xE2E0,
  addr_kRipper_Ilist_E2F4 = 0xE2F4,
  addr_kGripper_Sprmap_E43F = 0xE43F,
  addr_kGripper_Sprmap_E44B = 0xE44B,
  addr_kRipper_Ilist_E477 = 0xE477,
  addr_kRipper_Ilist_E48B = 0xE48B,
  addr_kLavaSeahorse_Ilist_E59B = 0xE59B,
  addr_kLavaSeahorse_Ilist_E5A1 = 0xE5A1,
  addr_kTimedShutter_Ilist_E998 = 0xE998,
  addr_kTimedShutter_Ilist_E99E = 0xE99E,
  addr_kTimedShutter_Ilist_E9A4 = 0xE9A4,
  addr_kTimedShutter_Ilist_E9AA = 0xE9AA,
  addr_kTimedShutter_Ilist_E9D4 = 0xE9D4,
  addr_kRisingFallingPlatform_Ilist_EDE7 = 0xEDE7,
};
enum Consts_A3 {
  addr_kSpritemap_Nothing_A3 = 0x804D,
  addr_kWaver_Ilist_86A7 = 0x86A7,
  addr_kMetalee_Ilist_8910 = 0x8910,
  addr_kFireflea_Ilist_8C2F = 0x8C2F,
  addr_kMaridiaFish_Ilist_902A = 0x902A,
  addr_kMaridiaFish_Ilist_903C = 0x903C,
  addr_kMaridiaFish_Ilist_9060 = 0x9060,
  addr_kMaridiaFish_Ilist_9072 = 0x9072,
  addr_kElevator_Ilist_94D6 = 0x94D6,
  addr_kPlatformThatFallsWithSamus_Ilist_9BBB = 0x9BBB,
  addr_kPlatformThatFallsWithSamus_Ilist_9BD1 = 0x9BD1,
  addr_kPlatformThatFallsWithSamus_Ilist_9BE7 = 0x9BE7,
  addr_kPlatformThatFallsWithSamus_Ilist_9BFD = 0x9BFD,
  addr_kPlatformThatFallsWithSamus_Ilist_9C13 = 0x9C13,
  addr_kPlatformThatFallsWithSamus_Ilist_9C29 = 0x9C29,
  addr_kPlatformThatFallsWithSamus_Ilist_9C3F = 0x9C3F,
  addr_kPlatformThatFallsWithSamus_Ilist_9C55 = 0x9C55,
  addr_kPlatformThatFallsWithSamus_Sprmap_A009 = 0xA009,
  addr_kPlatformThatFallsWithSamus_Sprmap_A015 = 0xA015,
  addr_kMochtroid_Ilist_A745 = 0xA745,
  addr_kMochtroid_Ilist_A759 = 0xA759,
  addr_kMaridiaRefillCandy_Ilist_B3C1 = 0xB3C1,
  addr_kBang_Ilist_B75E = 0xB75E,
  addr_kSkree_Ilist_C65E = 0xC65E,
  addr_stru_A3CCE2 = 0xCCE2,
  addr_stru_A3CCEA = 0xCCEA,
  addr_stru_A3CCF2 = 0xCCF2,
  addr_stru_A3CCFA = 0xCCFA,
  addr_stru_A3CD02 = 0xCD02,
  addr_stru_A3CD0A = 0xCD0A,
  addr_stru_A3CD12 = 0xCD12,
  addr_stru_A3CD1A = 0xCD1A,
  addr_stru_A3CD22 = 0xCD22,
  addr_stru_A3CD2A = 0xCD2A,
  addr_stru_A3CD32 = 0xCD32,
  addr_stru_A3CD3A = 0xCD3A,
  addr_kWreckedShipOrangeZoomer_Ilist_DFCB = 0xDFCB,
  addr_kWreckedShipOrangeZoomer_Ilist_DFE7 = 0xDFE7,
  addr_kWreckedShipOrangeZoomer_Ilist_E003 = 0xE003,
  addr_kWreckedShipOrangeZoomer_Ilist_E01F = 0xE01F,
  addr_locret_A3E08A = 0xE08A,
  addr_kMetroid_Ilist_E9CF = 0xE9CF,
  addr_kMetroid_Ilist_EA25 = 0xEA25,
};
enum Consts_A4 {
  addr_kSpritemap_Nothing_A4 = 0x804D,
  addr_kExtendedSpritemap_Nothing_A4 = 0x804F,
  addr_kCrocomire_Ilist_BADE = 0xBADE,
  addr_kCrocomire_Ilist_BAEA = 0xBAEA,
  addr_kCrocomire_Ilist_BB36 = 0xBB36,
  addr_kCrocomire_Ilist_BBCA = 0xBBCA,
  addr_kCrocomire_Ilist_BBCE = 0xBBCE,
  addr_kCrocomire_Ilist_BC30 = 0xBC30,
  addr_kCrocomire_Ilist_BC34 = 0xBC34,
  addr_kCrocomire_Ilist_BC56 = 0xBC56,
  addr_kCrocomire_Ilist_BCD8 = 0xBCD8,
  addr_kCrocomire_Ilist_BD2A = 0xBD2A,
  addr_kCrocomire_Ilist_BD8E = 0xBD8E,
  addr_kCrocomire_Ilist_BDA2 = 0xBDA2,
  addr_kCrocomire_Ilist_BDAE = 0xBDAE,
  addr_kCrocomire_Ilist_BDB2 = 0xBDB2,
  addr_kCrocomire_Ilist_BDB6 = 0xBDB6,
  addr_kCrocomire_Ilist_BE56 = 0xBE56,
  addr_kCrocomire_Ilist_BE7E = 0xBE7E,
  addr_kCrocomire_Ilist_BF3C = 0xBF3C,
  addr_kCrocomire_Ilist_BF62 = 0xBF62,
  addr_kCrocomire_Ilist_BF64 = 0xBF64,
  addr_kCrocomire_Ilist_BF6C = 0xBF6C,
  addr_kCrocomire_Ilist_BF72 = 0xBF72,
  addr_kCrocomire_Ilist_BF78 = 0xBF78,
  addr_kCrocomire_Ilist_BF7E = 0xBF7E,
  addr_kCrocomire_Ilist_BF86 = 0xBF86,
  addr_kCrocomire_Ilist_BF8C = 0xBF8C,
  addr_kCrocomire_Ilist_BF92 = 0xBF92,
  addr_kCrocomire_Ilist_BF98 = 0xBF98,
  addr_kCrocomire_Ilist_BFB0 = 0xBFB0,
  addr_kCrocomire_BigSprmap_D51C = 0xD51C,
  addr_kCrocomire_BigSprmap_D600 = 0xD600,
  addr_kCrocomire_Ilist_E14A = 0xE14A,
  addr_kCrocomire_Ilist_E158 = 0xE158,
  addr_kCrocomire_Ilist_E1CC = 0xE1CC,
  addr_kCrocomire_Ilist_E1D2 = 0xE1D2,
};
enum Consts_A5 {
  addr_kDraygon_Ilist_97B9 = 0x97B9,
  addr_kDraygon_Ilist_97BB = 0x97BB,
  addr_kDraygon_Ilist_97D1 = 0x97D1,
  addr_kDraygon_Ilist_97E7 = 0x97E7,
  addr_kDraygon_Ilist_9813 = 0x9813,
  addr_kDraygon_Ilist_9825 = 0x9825,
  addr_kDraygon_Ilist_9845 = 0x9845,
  addr_kDraygon_Ilist_9867 = 0x9867,
  addr_kDraygon_Ilist_9889 = 0x9889,
  addr_kDraygon_Ilist_98ED = 0x98ED,
  addr_kDraygon_Ilist_98FE = 0x98FE,
  addr_kDraygon_Ilist_9922 = 0x9922,
  addr_kDraygon_Ilist_9944 = 0x9944,
  addr_kDraygon_Ilist_997A = 0x997A,
  addr_kDraygon_Ilist_999C = 0x999C,
  addr_kDraygon_Ilist_99AE = 0x99AE,
  addr_kDraygon_Ilist_99B4 = 0x99B4,
  addr_kDraygon_Ilist_99BA = 0x99BA,
  addr_kDraygon_Ilist_99C0 = 0x99C0,
  addr_kDraygon_Ilist_99FC = 0x99FC,
  addr_kDraygon_Ilist_9A68 = 0x9A68,
  addr_kDraygon_Ilist_9AE8 = 0x9AE8,
  addr_kDraygon_Ilist_9B5A = 0x9B5A,
  addr_kDraygon_Ilist_9BDA = 0x9BDA,
  addr_kDraygon_Ilist_9C06 = 0x9C06,
  addr_kDraygon_Ilist_9C18 = 0x9C18,
  addr_kDraygon_Ilist_9C38 = 0x9C38,
  addr_kDraygon_Ilist_9C5A = 0x9C5A,
  addr_kDraygon_Ilist_9C90 = 0x9C90,
  addr_kDraygon_Ilist_9CB4 = 0x9CB4,
  addr_kDraygon_Ilist_9D1C = 0x9D1C,
  addr_kDraygon_Ilist_9D3E = 0x9D3E,
  addr_kDraygon_Ilist_9D50 = 0x9D50,
  addr_kDraygon_Ilist_9D56 = 0x9D56,
  addr_kDraygon_Ilist_9D5C = 0x9D5C,
  addr_kDraygon_Ilist_9D62 = 0x9D62,
  addr_kDraygon_Ilist_9D9E = 0x9D9E,
  addr_kDraygon_Ilist_9E21 = 0x9E21,
  addr_kDraygon_Ilist_9EA1 = 0x9EA1,
  addr_kDraygon_Ilist_9F15 = 0x9F15,
  addr_kDraygon_Palette = 0xA1F7,
  addr_kDraygon_MorePalettes2 = 0xA277,
  addr_word_A5A297 = 0xA297,
  addr_kDraygon_BigSprmap_C08F__plus__17 = 0xC0A0,
  addr_kDraygon_BigSprmap_C11B__plus__197 = 0xC1E0,
  addr_kDraygon_Ilist_E6B9 = 0xE6B9,
  addr_kDraygon_Ilist_E6C7 = 0xE6C7,
  addr_kDraygon_Ilist_E6D5 = 0xE6D5,
  addr_stru_A5E729 = 0xE729,
  addr_kDraygon_Ilist_E77D = 0xE77D,
};
enum Consts_A6 {
  addr_kBoulder_Ilist_86A7 = 0x86A7,
  addr_kBoulder_Ilist_86CB = 0x86CB,
  addr_kSpikeyPlatform_Ilist_8B29 = 0x8B29,
  addr_kFireGeyser_Ilist_8D1B = 0x8D1B,
  addr_kFireGeyser_Ilist_8DA9 = 0x8DA9,
  addr_kNuclearWaffle_Ilist_9490 = 0x9490,
  addr_stru_A699AE = 0x99AE,
  addr_stru_A699C6 = 0x99C6,
  addr_kFakeKraid_Ilist_99DC = 0x99DC,
  addr_stru_A699FC = 0x99FC,
  addr_stru_A69A14 = 0x9A14,
  addr_kFakeKraid_Ilist_9A2A = 0x9A2A,
  addr_kCeresRidley_Sprmap_A329 = 0xA329,
  addr_loc_A6A7F9 = 0xA7F9,
  addr_word_A6A9E3 = 0xA9E3,
  addr_word_A6AA01 = 0xAA01,
  addr_stru_A6AA2F = 0xAA2F,
  addr_stru_A6AA3F = 0xAA3F,
  addr_off_A6B38C = 0xB38C,
  addr_off_A6B39C = 0xB39C,
  addr_off_A6B3AC = 0xB3AC,
  addr_off_A6B3BC = 0xB3BC,
  addr_off_A6B3CC = 0xB3CC,
  addr_off_A6B3DC = 0xB3DC,
  addr_loc_A6B455 = 0xB455,
  addr_locret_A6BF19 = 0xBF19,
  addr_kBabyMetroid_Ilist_BF31 = 0xBF31,
  addr_byte_A6C15D = 0xC15D,
  addr_stru_A6C3B8 = 0xC3B8,
  addr_stru_A6C4CB = 0xC4CB,
  addr_locret_A6C600 = 0xC600,
  addr_stru_A6C987 = 0xC987,
  addr_stru_A6C997 = 0xC997,
  addr_stru_A6C9A7 = 0xC9A7,
  addr_stru_A6C9B7 = 0xC9B7,
  addr_stru_A6C9C7 = 0xC9C7,
  addr_stru_A6C9D7 = 0xC9D7,
  addr_stru_A6C9E7 = 0xC9E7,
  addr_stru_A6C9F7 = 0xC9F7,
  addr_stru_A6CA07 = 0xCA07,
  addr_stru_A6CA17 = 0xCA17,
  addr_stru_A6CA27 = 0xCA27,
  addr_stru_A6CA37 = 0xCA37,
  addr_kRidleysExplosion_Ilist_CA47 = 0xCA47,
  addr_kRidleysExplosion_Ilist_CA4D = 0xCA4D,
  addr_kRidleysExplosion_Ilist_CA53 = 0xCA53,
  addr_word_A6D36E = 0xD36E,
  addr_word_A6D37C = 0xD37C,
  addr_word_A6D38A = 0xD38A,
  addr_word_A6D398 = 0xD398,
  addr_word_A6D3A6 = 0xD3A6,
  addr_word_A6DA71 = 0xDA71,
  addr_off_A6DAD0 = 0xDAD0,
  addr_off_A6DAD4 = 0xDAD4,
  addr_word_A6E16F = 0xE16F,
  addr_word_A6E1CF = 0xE1CF,
  addr_kRidley_Ilist_E538 = 0xE538,
  addr_kRidley_Ilist_E548 = 0xE548,
  addr_kRidley_Ilist_E658 = 0xE658,
  addr_kRidley_Ilist_E690 = 0xE690,
  addr_kRidley_Ilist_E6C8 = 0xE6C8,
  addr_kRidley_Ilist_E6F0 = 0xE6F0,
  addr_kRidley_Ilist_E706 = 0xE706,
  addr_kRidley_Ilist_E73A = 0xE73A,
  addr_kRidley_Ilist_E91D = 0xE91D,
  addr_kCeresDoor_Palette__plus__2 = 0xF4EE,
  addr_word_A6F50C__plus__2 = 0xF50E,
  addr_kCeresDoor_Sprmap_FAC7 = 0xFAC7,
  addr_stru_A6FCE1 = 0xFCE1,
  addr_stru_A6FCF9 = 0xFCF9,
};
enum Consts_A7 {
  addr_kSpritemap_Nothing_A7 = 0x804D,
  addr_kKraid_Ilist_86E7 = 0x86E7,
  addr_kKraid_Ilist_86ED = 0x86ED,
  addr_kKraid_Ilist_86F3 = 0x86F3,
  addr_off_A787BB = 0x87BB,
  addr_kKraid_Ilist_87BD = 0x87BD,
  addr_off_A78885 = 0x8885,
  addr_kKraid_Ilist_8887 = 0x8887,
  addr_kKraid_Ilist_89F3 = 0x89F3,
  addr_kKraid_Ilist_8A41 = 0x8A41,
  addr_kKraid_Ilist_8AA4 = 0x8AA4,
  addr_kKraid_Ilist_8AF0 = 0x8AF0,
  addr_kKraid_Ilist_8AFE = 0x8AFE,
  addr_kKraid_Ilist_8B04 = 0x8B04,
  addr_kKraid_Ilist_8B0A = 0x8B0A,
  addr_kKraid_Sprmap_8C6C = 0x8C6C,
  addr_stru_A796DA = 0x96DA,
  addr_stru_A7974A__plus__8 = 0x9752,
  addr_stru_A79764__plus__8 = 0x976C,
  addr_kKraidTilemaps_0 = 0x97C8,
  addr_kKraidTilemaps_1 = 0x9AC8,
  addr_kKraidTilemaps_2 = 0x9DC8,
  addr_kKraidTilemaps_3 = 0xA0C8,
  addr_kKraid_Sprmap_A5DF = 0xA5DF,
  addr_kKraidsRoomBg = 0xA716,
  addr_locret_A7B831 = 0xB831,
  addr_kKraid_Ilist_CC41 = 0xCC41,
  addr_kKraid_Ilist_CC47 = 0xCC47,
  addr_kKraid_Ilist_CC4D = 0xCC4D,
  addr_kKraid_Ilist_CC53 = 0xCC53,
  addr_kKraid_Ilist_CC81 = 0xCC81,
  addr_kKraid_Ilist_CC91 = 0xCC91,
  addr_kKraid_Ilist_CC9D = 0xCC9D,
  addr_kKraid_Ilist_CCEB = 0xCCEB,
  addr_kPhantoonMoveData = 0xE3D2,
  addr_kEtecoon_Ilist_E81E = 0xE81E,
  addr_stru_A7E828 = 0xE828,
  addr_kEtecoon_Ilist_E83C = 0xE83C,
  addr_kEtecoon_Ilist_E854 = 0xE854,
  addr_stru_A7E862 = 0xE862,
  addr_kEtecoon_Ilist_E870 = 0xE870,
  addr_kEtecoon_Ilist_E876 = 0xE876,
  addr_stru_A7E880 = 0xE880,
  addr_kEtecoon_Ilist_E894 = 0xE894,
  addr_stru_A7E898 = 0xE898,
  addr_kEtecoon_Ilist_E8AC = 0xE8AC,
  addr_kEtecoon_Ilist_E8C8 = 0xE8C8,
  addr_kEtecoon_Ilist_E8CE = 0xE8CE,
  addr_kEtecoon_Ilist_E8D6 = 0xE8D6,
  addr_kDachora_Palette = 0xF225,
  addr_kDachora_Ilist_F345 = 0xF345,
  addr_kDachora_Ilist_F399 = 0xF399,
  addr_kDachora_Ilist_F3C9 = 0xF3C9,
  addr_kDachora_Ilist_F3F7 = 0xF3F7,
  addr_kDachora_Ilist_F3FF = 0xF3FF,
  addr_kDachora_Ilist_F407 = 0xF407,
  addr_kDachora_Ilist_F45B = 0xF45B,
  addr_kDachora_Ilist_F48B = 0xF48B,
  addr_kDachora_Ilist_F4B3 = 0xF4B3,
  addr_kDachora_Ilist_F4B9 = 0xF4B9,
  addr_kDachora_Ilist_F4C1 = 0xF4C1,
};
enum Consts_A8 {
  addr_kSpritemap_Nothing_A8 = 0x804D,
  addr_kMiniDraygon_Ilist_86A7 = 0x86A7,
  addr_kMiniDraygon_Ilist_86C3 = 0x86C3,
  addr_kMiniDraygon_Ilist_870B = 0x870B,
  addr_kMiniDraygon_Ilist_8727 = 0x8727,
  addr_kMiniDraygon_Ilist_876F = 0x876F,
  addr_kMiniDraygon_Ilist_8775 = 0x8775,
  addr_kMorphBallEye_Ilist_8FF0 = 0x8FF0,
  addr_stru_A88FFC = 0x8FFC,
  addr_kMorphBallEye_Ilist_9002 = 0x9002,
  addr_stru_A8900E = 0x900E,
  addr_kMorphBallEye_Ilist_9014 = 0x9014,
  addr_kMorphBallEye_Ilist_9026 = 0x9026,
  addr_off_A896D7 = 0x96D7,
  addr_off_A896DF = 0x96DF,
  addr_kWreckedShipGhost_Ilist_9A8C = 0x9A8C,
  addr_loc_A89E90 = 0x9E90,
  addr_kYappingMaw_Ilist_9F6F = 0x9F6F,
  addr_kYappingMaw_Ilist_9FC7 = 0x9FC7,
  addr_kYappingMaw_Ilist_A01F = 0xA01F,
  addr_off_A8A025 = 0xA025,
  addr_kYappingMaw_Ilist_A03D = 0xA03D,
  addr_kYappingMaw_Ilist_A05B = 0xA05B,
  addr_off_A8A061 = 0xA061,
  addr_kYappingMaw_Ilist_A079 = 0xA079,
  addr_kKago_Ilist_AB1E = 0xAB1E,
  addr_kKago_Ilist_AB32 = 0xAB32,
  addr_kNorfairLavaMan_Ilist_AC9C = 0xAC9C,
  addr_kNorfairLavaMan_Ilist_ACB0 = 0xACB0,
  addr_kNorfairLavaMan_Ilist_ACDE = 0xACDE,
  addr_kNorfairLavaMan_Ilist_AD0C = 0xAD0C,
  addr_kNorfairLavaMan_Ilist_AD3C = 0xAD3C,
  addr_kNorfairLavaMan_Ilist_AD50 = 0xAD50,
  addr_kNorfairLavaMan_Ilist_AD7E = 0xAD7E,
  addr_kNorfairLavaMan_Ilist_ADAC = 0xADAC,
  addr_kNorfairLavaMan_Ilist_ADDC = 0xADDC,
  addr_kNorfairLavaMan_Ilist_AE0C = 0xAE0C,
  addr_kBeetom_Ilist_B696 = 0xB696,
  addr_kBeetom_Ilist_B6AC = 0xB6AC,
  addr_kBeetom_Ilist_B6CC = 0xB6CC,
  addr_kBeetom_Ilist_B6F2 = 0xB6F2,
  addr_kBeetom_Ilist_B708 = 0xB708,
  addr_kBeetom_Ilist_B728 = 0xB728,
  addr_kMaridiaFloater_Ilist_C163 = 0xC163,
  addr_kMaridiaFloater_Ilist_C173 = 0xC173,
  addr_kMaridiaFloater_Ilist_C183 = 0xC183,
  addr_kMaridiaFloater_Ilist_C191 = 0xC191,
  addr_stru_A8C199 = 0xC199,
  addr_kWreckedShipRobot_Ilist_C6E5 = 0xC6E5,
  addr_stru_A8C6E9 = 0xC6E9,
  addr_kWreckedShipRobot_Ilist_C73F = 0xC73F,
  addr_kWreckedShipRobot_Ilist_C7BB = 0xC7BB,
  addr_kWreckedShipRobot_Ilist_C833 = 0xC833,
  addr_kWreckedShipRobot_Ilist_C8B1 = 0xC8B1,
  addr_kWreckedShipRobot_Ilist_C8BD = 0xC8BD,
  addr_kWreckedShipRobot_Ilist_C8D1 = 0xC8D1,
  addr_kWreckedShipRobot_Ilist_C91B = 0xC91B,
  addr_kWreckedShipRobot_Ilist_C92D = 0xC92D,
  addr_kWreckedShipRobot_Ilist_C985 = 0xC985,
  addr_kWreckedShipRobot_Ilist_CA01 = 0xCA01,
  addr_kWreckedShipRobot_Ilist_CA7D = 0xCA7D,
  addr_kWreckedShipRobot_Ilist_CAFD = 0xCAFD,
  addr_kWreckedShipRobot_Ilist_CB09 = 0xCB09,
  addr_kWreckedShipRobot_Ilist_CB1D = 0xCB1D,
  addr_kWreckedShipRobot_Ilist_CB65 = 0xCB65,
  addr_loc_A8CF18 = 0xCF18,
  addr_loc_A8CF26 = 0xCF26,
  addr_loc_A8D02E = 0xD02E,
  addr_kMaridiaPuffer_Ilist_D841 = 0xD841,
  addr_kMaridiaPuffer_Ilist_D855 = 0xD855,
  addr_kWalkingLavaSeahorse_Ilist_DBE7 = 0xDBE7,
  addr_stru_A8DBE9 = 0xDBE9,
  addr_kWalkingLavaSeahorse_Ilist_DC03 = 0xDC03,
  addr_stru_A8DC4B = 0xDC4B,
  addr_kWalkingLavaSeahorse_Ilist_DC51 = 0xDC51,
  addr_kWalkingLavaSeahorse_Ilist_DC57 = 0xDC57,
  addr_stru_A8DC59 = 0xDC59,
  addr_kWalkingLavaSeahorse_Ilist_DC73 = 0xDC73,
  addr_stru_A8DCBB = 0xDCBB,
  addr_kWalkingLavaSeahorse_Ilist_DCC1 = 0xDCC1,
  addr_kWreckedShipSpark_Ilist_E5A7 = 0xE5A7,
  addr_kWreckedShipSpark_Ilist_E5E5 = 0xE5E5,
  addr_kBlueBrinstarFaceBlock_Ilist_E80C = 0xE80C,
  addr_kBlueBrinstarFaceBlock_Ilist_E81A = 0xE81A,
  addr_kBlueBrinstarFaceBlock_Ilist_E828 = 0xE828,
  addr_kKiHunter_Ilist_E9FA = 0xE9FA,
  addr_kKiHunter_Ilist_EA08 = 0xEA08,
  addr_kKiHunter_Ilist_EA24 = 0xEA24,
  addr_kKiHunter_Ilist_EA32 = 0xEA32,
  addr_kKiHunter_Ilist_EA4E = 0xEA4E,
  addr_kKiHunter_Ilist_EA5E = 0xEA5E,
  addr_kKiHunter_Ilist_EA7E = 0xEA7E,
  addr_kKiHunter_Ilist_EA8A = 0xEA8A,
  addr_kKiHunter_Ilist_EAA6 = 0xEAA6,
  addr_kKiHunter_Ilist_EAC2 = 0xEAC2,
  addr_kKiHunter_Ilist_EADA = 0xEADA,
  addr_kKiHunter_Ilist_EAF2 = 0xEAF2,
  addr_kKiHunter_Ilist_EB10 = 0xEB10,
  addr_locret_A8F5E3 = 0xF5E3,
};
enum Consts_A9 {
  addr_locret_A98AE4 = 0x8AE4,
  addr_stru_A98AE5 = 0x8AE5,
  addr_stru_A98AF5 = 0x8AF5,
  addr_stru_A98B05 = 0x8B05,
  addr_stru_A98B25 = 0x8B25,
  addr_stru_A98F8F = 0x8F8F,
  addr_stru_A98FC7 = 0x8FC7,
  addr_stru_A98FE5 = 0x8FE5,
  addr_stru_A99003 = 0x9003,
  addr_stru_A9902F = 0x902F,
  addr_kMotherBrainsBrain_Palette = 0x9472,
  addr_kMotherBrainPalette_0 = 0x9492,
  addr_kMotherBrainPalette_1 = 0x94B2,
  addr_kMotherBrainPalette_2 = 0x94D2,
  addr_kMotherBrainPalette_3 = 0x94F2,
  addr_kMotherBrainPalette_4 = 0x9512,
  addr_kMotherBrainPalette_5 = 0x9532,
  addr_kMotherBrain_Ilist_97A4 = 0x97A4,
  addr_kMotherBrain_Ilist_98C6 = 0x98C6,
  addr_kMotherBrain_Ilist_99AA = 0x99AA,
  addr_kMotherBrain_Ilist_99C6 = 0x99C6,
  addr_kMotherBrain_Ilist_99E2 = 0x99E2,
  addr_kMotherBrain_Ilist_99F2 = 0x99F2,
  addr_kMotherBrain_Ilist_9A02 = 0x9A02,
  addr_kMotherBrain_Ilist_9A0A = 0x9A0A,
  addr_kMotherBrain_Ilist_9A26 = 0x9A26,
  addr_kMotherBrain_Ilist_9A42 = 0x9A42,
  addr_kMotherBrain_Ilist_9B7F = 0x9B7F,
  addr_kMotherBrain_Ilist_9BB3 = 0x9BB3,
  addr_kMotherBrain_Ilist_9BE7 = 0x9BE7,
  addr_kMotherBrain_Ilist_9C13 = 0x9C13,
  addr_stru_A99C21 = 0x9C21,
  addr_kMotherBrain_Ilist_9C29 = 0x9C29,
  addr_kMotherBrain_Ilist_9C39 = 0x9C39,
  addr_stru_A99C47 = 0x9C47,
  addr_stru_A99C5F = 0x9C5F,
  addr_kMotherBrain_Ilist_9C77 = 0x9C77,
  addr_kMotherBrain_Ilist_9C87 = 0x9C87,
  addr_stru_A99C9F = 0x9C9F,
  addr_stru_A99CD1 = 0x9CD1,
  addr_kMotherBrain_Ilist_9D25 = 0x9D25,
  addr_kMotherBrain_Ilist_9D3D = 0x9D3D,
  addr_kMotherBrain_Ilist_9D7F = 0x9D7F,
  addr_kMotherBrain_Ilist_9DB1 = 0x9DB1,
  addr_kMotherBrain_Ilist_9DBB = 0x9DBB,
  addr_kMotherBrain_Ilist_9ECC = 0x9ECC,
  addr_kMotherBrain_Ilist_9F00 = 0x9F00,
  addr_kMotherBrain_Ilist_9F34 = 0x9F34,
  addr_kMotherBrain_Ilist_9F6C = 0x9F6C,
  addr_kMotherBrain_Sprmap_A694 = 0xA694,
  addr_word_A9B109 = 0xB109,
  addr_word_A9B10F = 0xB10F,
  addr_word_A9B427 = 0xB427,
  addr_byte_A9B6DC = 0xB6DC,
  addr_byte_A9B6DF = 0xB6DF,
  addr_stru_A9BE28 = 0xBE28,
  addr_locret_A9C18D = 0xC18D,
  addr_locret_A9C353 = 0xC353,
  addr_loc_A9C49C = 0xC49C,
  addr_loc_A9C959 = 0xC959,
  addr_stru_A9CA24 = 0xCA24,
  addr_kShitroid_Ilist_CFA2 = 0xCFA2,
  addr_kShitroid_Ilist_CFB8 = 0xCFB8,
  addr_kShitroid_Ilist_CFCE = 0xCFCE,
  addr_stru_A9D046 = 0xD046,
  addr_word_A9D082 = 0xD082,
  addr_kDeadTorizo_Ilist_D6DC = 0xD6DC,
  addr_kDeadTorizo_Sprmap_D761 = 0xD761,
  addr_kDeadTorizo_Hitbox_D77C = 0xD77C,
  addr_stru_A9DD58 = 0xDD58,
  addr_stru_A9DD68 = 0xDD68,
  addr_stru_A9DD78 = 0xDD78,
  addr_stru_A9DE08 = 0xDE08,
  addr_kDeadMonsters_Ilist_ECAC = 0xECAC,
  addr_kDeadMonsters_Ilist_ECE3 = 0xECE3,
  addr_kDeadMonsters_Ilist_ECE9 = 0xECE9,
  addr_kDeadMonsters_Ilist_ECEF = 0xECEF,
  addr_word_A9F6D1 = 0xF6D1,
  addr_word_A9F711 = 0xF711,
  addr_kDeadSidehopper_Palette_0 = 0xF8A6,
  addr_word_A9F8C6 = 0xF8C6,
  addr_kShitroidInCutscene_Palette = 0xF8E6,
  addr_kShitroid_Ilist_F906 = 0xF906,
  addr_kShitroid_Ilist_F90E = 0xF90E,
  addr_kShitroid_Ilist_F924 = 0xF924,
  addr_kShitroid_Ilist_F93A = 0xF93A,
};
enum Consts_AA {
  addr_kSpritemap_Nothing_AA = 0x804D,
  addr_kTorizo_ExtSprmap_87D0 = 0x87D0,
  addr_kTorizo_Ilist_B0E5 = 0xB0E5,
  addr_kTorizo_Ilist_B155 = 0xB155,
  addr_kTorizo_Ilist_B1C8 = 0xB1C8,
  addr_kTorizo_Ilist_B962 = 0xB962,
  addr_off_AABC78 = 0xBC78,
  addr_kTorizo_Ilist_BD0E = 0xBD0E,
  addr_kTorizo_Ilist_BDD8 = 0xBDD8,
  addr_off_AAC0F2 = 0xC0F2,
  addr_kTorizo_Ilist_C188 = 0xC188,
  addr_locret_AAC95E = 0xC95E,
  addr_kTorizo_Ilist_CDE1 = 0xCDE1,
  addr_kTorizo_Ilist_CE43 = 0xCE43,
  addr_kTorizo_Ilist_CEA5 = 0xCEA5,
  addr_kTorizo_Ilist_CEFF = 0xCEFF,
  addr_kTorizo_Ilist_D1F1 = 0xD1F1,
  addr_kTorizo_Ilist_D203 = 0xD203,
  addr_kTorizo_Ilist_D2AD = 0xD2AD,
  addr_kTorizo_Ilist_D2BF = 0xD2BF,
  addr_kShaktool_Ilist_E3A7 = 0xE3A7,
  addr_kShaktool_Ilist_E461 = 0xE461,
};
enum Consts_AD {
  addr_kTurnOffLightsForShitroidDeath = 0xF22F,
};
enum Consts_B2 {
  addr_kSpacePirates_Ilist_ECC0 = 0xECC0,
  addr_kSpacePirates_Ilist_ECE4 = 0xECE4,
  addr_off_B2ECEC = 0xECEC,
  addr_kSpacePirates_Ilist_ED36 = 0xED36,
  addr_kSpacePirates_Ilist_ED80 = 0xED80,
  addr_kSpacePirates_Ilist_EDA4 = 0xEDA4,
  addr_off_B2EDAC = 0xEDAC,
  addr_kSpacePirates_Ilist_EDF6 = 0xEDF6,
  addr_kSpacePirates_Ilist_F15C = 0xF15C,
  addr_kSpacePirates_Ilist_F1C4 = 0xF1C4,
  addr_kSpacePirates_Ilist_F22E = 0xF22E,
  addr_kSpacePirates_Ilist_F270 = 0xF270,
  addr_kSpacePirates_Ilist_F2A0 = 0xF2A0,
  addr_kSpacePirates_Ilist_F2B2 = 0xF2B2,
  addr_kSpacePirates_Ilist_F2DA = 0xF2DA,
  addr_kSpacePirates_Ilist_F2F8 = 0xF2F8,
  addr_kSpacePirates_Ilist_F32E = 0xF32E,
  addr_kSpacePirates_Ilist_F34A = 0xF34A,
  addr_kSpacePirates_Ilist_F3B2 = 0xF3B2,
  addr_kSpacePirates_Ilist_F420 = 0xF420,
  addr_kSpacePirates_Ilist_F462 = 0xF462,
  addr_kSpacePirates_Ilist_F492 = 0xF492,
  addr_kSpacePirates_Ilist_F4A4 = 0xF4A4,
  addr_kSpacePirates_Ilist_F4CC = 0xF4CC,
  addr_kSpacePirates_Ilist_F4EA = 0xF4EA,
  addr_kSpacePirates_Ilist_F51A = 0xF51A,
  addr_kSpacePirates_Ilist_FB4C = 0xFB4C,
  addr_kSpacePirates_Ilist_FB58 = 0xFB58,
  addr_kSpacePirates_Ilist_FB64 = 0xFB64,
  addr_kSpacePirates_Ilist_FB8C = 0xFB8C,
  addr_kSpacePirates_Ilist_FBC6 = 0xFBC6,
  addr_kSpacePirates_Ilist_FBE6 = 0xFBE6,
  addr_kSpacePirates_Ilist_FC0E = 0xFC0E,
  addr_kSpacePirates_Ilist_FC48 = 0xFC48,
};
enum Consts_B3 {
  addr_kSpritemap_Nothing_B3 = 0x804D,
  addr_kUnusedSpinningTurtleEye_Ilist_86A7 = 0x86A7,
  addr_kBrinstarPipeBug_Ilist_87AB = 0x87AB,
  addr_kBrinstarPipeBug_Ilist_8A1D = 0x8A1D,
  addr_kNorfairPipeBug_Ilist_8AE1 = 0x8AE1,
  addr_kNorfairPipeBug_Ilist_8B05 = 0x8B05,
  addr_kNorfairPipeBug_Ilist_8B21 = 0x8B21,
  addr_kNorfairPipeBug_Ilist_8B45 = 0x8B45,
  addr_kBrinstarYellowPipeBug_Ilist_8EFC = 0x8EFC,
  addr_kBrinstarYellowPipeBug_Ilist_8F10 = 0x8F10,
  addr_kBrinstarYellowPipeBug_Ilist_8F24 = 0x8F24,
  addr_kBrinstarYellowPipeBug_Ilist_8F38 = 0x8F38,
  addr_kBotwoon_Ilist_9389 = 0x9389,
  addr_stru_B3E150 = 0xE150,
  addr_loc_B3E28C = 0xE28C,
  addr_kEscapeEtecoon_Ilist_E556 = 0xE556,
  addr_kEscapeEtecoon_Ilist_E582 = 0xE582,
  addr_kEscapeEtecoon_Ilist_E5AE = 0xE5AE,
  addr_kEscapeEtecoon_Ilist_E5DA = 0xE5DA,
  addr_kEscapeDachora_Ilist_E964 = 0xE964,
};
enum Consts_B4 {
  addr_kSpriteObject_Ilist_C3BA = 0xC3BA,
  addr_kSpriteObject_Ilist_C4B6 = 0xC4B6,
  addr_asc_B4DD89 = 0xDD89,
  addr_stru_B4EC1C = 0xEC1C,
};
enum Consts_B7 {
  addr_kDeadTorizo_TileData = 0xA800,
  addr_kDeadMonsters_TileData = 0xC000,
  addr_kMotherBrain_Misc_TileData = 0xCE00,

};

static inline OamEnt *gOamEnt(int v) { return (OamEnt *)&g_ram[0x370 + v]; }
static inline VramWriteEntry *gVramWriteEntry(int a) { return (VramWriteEntry *)&g_ram[0xd0 + a]; }
struct DoorDef; static inline DoorDef *get_DoorDef(uint16 a) { return (DoorDef *)RomPtr(0x830000 | a); }
struct RoomDefHeader; static inline RoomDefHeader *get_RoomDefHeader(uint16 a) { return (RoomDefHeader *)RomPtr(0x8F0000 | a); }
struct RoomDefRoomstate; static inline RoomDefRoomstate *get_RoomDefRoomstate(uint16 a) { return (RoomDefRoomstate *)RomPtr(0x8F0000 | a); }
struct StateHeaderTiles; static inline StateHeaderTiles *get_StateHeaderTiles(uint16 a) { return (StateHeaderTiles *)RomPtr(0x8F0000 | a); }
struct EnemyDef_A2; static inline EnemyDef_A2 *get_EnemyDef_A2(uint16 a) { return (EnemyDef_A2 *)RomPtr(0xA00000 | a); }
struct EnemyTileset; static inline EnemyTileset *get_EnemyTileset(uint16 a) { return (EnemyTileset *)RomPtr(0xB40000 | a); }
struct RoomPlmEntry; static inline RoomPlmEntry *get_RoomPlmEntry(uint16 a) { return (RoomPlmEntry *)RomPtr(0x8F0000 | a); }
struct EnemyProjectileDef; static inline EnemyProjectileDef *get_EnemyProjectileDef(uint16 a) { return (EnemyProjectileDef *)RomPtr(0x860000 | a); }
struct Vulnerability; static inline Vulnerability *get_Vulnerability(uint16 a) { return (Vulnerability *)RomPtr(0xB40000 | a); }
struct ExtendedSpriteMap; static inline ExtendedSpriteMap *get_ExtendedSpriteMap(uint8 db, uint16 a) { return (ExtendedSpriteMap *)RomPtr(db << 16 | a); }
struct Hitbox; static inline Hitbox *get_Hitbox(uint8 db, uint16 a) { return (Hitbox *)RomPtr(db << 16 | a); }
struct Mode7CgvmWriteQueue; static inline Mode7CgvmWriteQueue *get_Mode7CgvmWriteQueue(uint16 a) { return (Mode7CgvmWriteQueue *)RomPtr(0x800000 | a); }
struct PoseEntry; static inline PoseEntry *get_PoseEntry(uint16 a) { return (PoseEntry *)RomPtr(0x910000 | a); }
struct ProjectileDataTable; static inline ProjectileDataTable *get_ProjectileDataTable(uint16 a) { return (ProjectileDataTable *)RomPtr(0x930000 | a); }
struct DemoInputObject; static inline DemoInputObject *get_DemoInputObject(uint16 a) { return (DemoInputObject *)RomPtr(0x910000 | a); }
struct DemoRoomData; static inline DemoRoomData *get_DemoRoomData(uint16 a) { return (DemoRoomData *)RomPtr(0x820000 | a); }
struct DemoSetDef; static inline DemoSetDef *get_DemoSetDef(uint16 a) { return (DemoSetDef *)RomPtr(0x910000 | a); }
struct EnemyPopulation; static inline EnemyPopulation *get_EnemyPopulation(uint8 db, uint16 a) { return (EnemyPopulation *)RomPtr(db << 16 | a); }
struct FxDef; static inline FxDef *get_FxDef(uint16 a) { return (FxDef *)RomPtr(0x830000 | a); }
struct LoadBg_E; static inline LoadBg_E *get_LoadBg_E(uint16 a) { return (LoadBg_E *)RomPtr(0x8F0000 | a); }
struct Mode7VramWriteQueue; static inline Mode7VramWriteQueue *get_Mode7VramWriteQueue(uint16 a) { return (Mode7VramWriteQueue *)RomPtr(0xA60000 | a); }
struct ProjectileInstr; static inline ProjectileInstr *get_ProjectileInstr(uint16 a) { return (ProjectileInstr *)RomPtr(0x930000 | a); }
struct PlmHeader_Size4; static inline PlmHeader_Size4 *get_PlmHeader_Size4(uint16 a) { return (PlmHeader_Size4 *)RomPtr(0x840000 | a); }
struct PlmHeader_Size6; static inline PlmHeader_Size6 *get_PlmHeader_Size6(uint16 a) { return (PlmHeader_Size6 *)RomPtr(0x840000 | a); }
struct RoomDefStateSelect_E6E5_Finish; static inline RoomDefStateSelect_E6E5_Finish *get_RoomDefStateSelect_E6E5_Finish(uint16 a) { return (RoomDefStateSelect_E6E5_Finish *)RomPtr(0x8F0000 | a); }
struct SamusSpeedTableEntry; static inline SamusSpeedTableEntry *get_SamusSpeedTableEntry(uint16 a) { return (SamusSpeedTableEntry *)RomPtr(0x900000 | a); }
struct SpriteDrawEnt; static inline SpriteDrawEnt *get_SpriteDrawEnt(uint16 a) { return (SpriteDrawEnt *)RomPtr(0xA60000 | a); }
struct SamusTileAnimationDefs; static inline SamusTileAnimationDefs *get_SamusTileAnimationDefs(uint16 a) { return (SamusTileAnimationDefs *)RomPtr(0x920000 | a); }
struct PalFxDef; static inline PalFxDef *get_PalFxDef(uint16 a) { return (PalFxDef *)RomPtr(0x8D0000 | a); }
struct Mode7ObjectDef; static inline Mode7ObjectDef *get_Mode7ObjectDef(uint16 a) { return (Mode7ObjectDef *)RomPtr(0x8B0000 | a); }
static inline Ram7800_Default *gRam7800_Default(uint16 a) { return (Ram7800_Default *)&g_ram[0x7800 + a]; }
static inline Mode7CgvmWriteQueue *get_Mode7CgvmWriteQueue_RAM(uint16 a) { return (Mode7CgvmWriteQueue *)RomPtr_RAM(a); }

#pragma pack(pop)
